#============ e2e-kind-config ====================

# iptables or ipvs, default iptables
E2E_KUBE_PROXY_MODE ?= iptables

K8S_IPV4_SERVICE_CIDR = 10.233.0.0/18
K8S_IPV6_SERVICE_CIDR = fd00:10:233::/116

CLUSTER_POD_SUBNET_V4 = 10.233.64.0/18
CLUSTER_POD_SUBNET_V6 = fd00:10:233:64::/64
CILIUM_CLUSTER_POD_SUBNET_V4 = 10.244.64.0/18
CILIUM_CLUSTER_POD_SUBNET_V6 = fd00:10:244::/112

# ipv4 or ipv6 or dual, default ipv4
E2E_IP_FAMILY ?= dual

# kubernetes version
E2E_KIND_IMAGE_TAG ?= v1.27.1
# with kind default version
# E2E_KIND_IMAGE_TAG ?= 

# disable default cni, default true
E2E_DISABLE_DEFAULT_CNI ?= true

INSTALL_MACVLAN ?= true

INSTALL_SPIDER ?= true

INSTALL_MULTUS ?= true

INSTALL_KRUISE ?= true

INSTALL_DEFAULT_CNI ?= true

INSTALL_CALICO ?= true

INSTALL_CILIUM ?= true

INSTALL_SPIDERDOCTOR ?= true

INSTALL_NETTOOLS ?= false

CALICO_VERSION ?= v3.25.0

CNI_PACKAGE_VERSION ?= v1.3.0

#============ ginkgo-custom-flag ====================
E2E_CLUSTER_NAME ?= spider

RELEASE_NAME ?= spiderpool
RELEASE_NAMESPACE ?= kube-system

# multi flag separated by commas,like setup,ippool
E2E_GINKGO_LABELS ?=

GINKGO_OPTION ?=

E2E_TIMEOUT ?= 60m

E2E_GINKGO_PROCS ?= 4

E2E_SPIDERPOOL_ENABLE_SUBNET ?= true
E2E_SPIDERPOOL_ENABLE_COORDINATOR ?= true
E2E_SPIDERPOOL_ENABLE_MULTUSCONFIG ?= true

#============Image version===========
TEST_IMAGE_NAME := alpine:latest

#USE_TLS_METHOD := certmanager
#USE_TLS_METHOD := provided
USE_TLS_METHOD := auto

IMAGE_PYROSCOPE_NAME := pyroscope/pyroscope:latest

CERT_MANAGER_VERSION := v1.8.0
IMAGE_CERT_MANAGER_REPO := quay.io/jetstack
IMAGE_CERT_MANAGER_NAME := $(IMAGE_CERT_MANAGER_REPO)/cert-manager-cainjector:$(CERT_MANAGER_VERSION) $(IMAGE_CERT_MANAGER_REPO)/cert-manager-cainjector:$(CERT_MANAGER_VERSION) $(IMAGE_CERT_MANAGER_REPO)/cert-manager-webhook:$(CERT_MANAGER_VERSION) $(IMAGE_CERT_MANAGER_REPO)/cert-manager-controller:$(CERT_MANAGER_VERSION)
CERT_MANAGER_ISSUER_NAME := selfsigned

TEST_VLAN_GATEWAY_IMAGE := centos/tools:latest

#================= multus
MULTUS_CNI_NAMESPACE := kube-system
MULTUS_DEFAULT_CNI_CALICO := k8s-pod-network
MULTUS_DEFAULT_CNI_CILIUM := cilium
MULTUS_DEFAULT_CNI_VLAN0 := macvlan-vlan0-underlay
MULTUS_DEFAULT_CNI_VLAN100 := macvlan-vlan100-underlay
MULTUS_DEFAULT_CNI_VLAN200 := macvlan-vlan200-underlay
MULTUS_ADDITIONAL_CNI_VLAN100 := macvlan-vlan100-overlay
MULTUS_ADDITIONAL_CNI_VLAN200 := macvlan-vlan200-overlay


#================= calico
CALICO_VERSION ?= v3.25.0
CALICO_IMAGE_REPO ?= docker.io
CALICO_AUTODETECTION_METHOD ?= "kubernetes-internal-ip"

#================= cilium
CILIUM_VERSION ?= v1.13.3

#================= spiderdoctor
SPIDERDOCTOR_VERSION ?= v0.3.0
SPIDERDOCTOR_IMAGE_REPO ?= ghcr.io
SPIDERDOCTOR_REPORT_PATH=/var/log/spiderdoctor/controller

#====== pyroscope
PYROSCOPE_CONTAINER_NAME := e2e-pyroscope
PYROSCOPE_LOCAL_PORT := 4040

#============Tmp Path================
# do not modify this ,it is also written on CI workflow file
DOWNLOAD_DIR := $(ROOT_DIR)/test/.download
CLUSTER_DIR := $(ROOT_DIR)/test/.cluster
E2E_KUBECONFIG := $(CLUSTER_DIR)/$(E2E_CLUSTER_NAME)/.kube/config

#=============http_proxy=============
http_proxy ?=

E2E_LOG_FILE ?= $(ROOT_DIR)/test/e2edebugLog.txt
