{
 "title": "Spiderpool RDMA | Pod",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(rdma_tx_vport_rdma_unicast_bytes_total{pod_namespace=~\"$namespace\"}, pod_namespace)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(rdma_tx_vport_rdma_unicast_bytes_total{}, node_name)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(rdma_tx_vport_rdma_unicast_bytes_total{pod_namespace=~\"$namespace\"}, pod_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Pod Level", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bandwidth | Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(rdma_rx_vport_rdma_unicast_bytes_total{pod_name!=\"\", pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[$__rate_interval]) + rate(rdma_rx_vport_rdma_multicast_bytes_total{pod_name!=\"\", pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[$__rate_interval]) ",
     "legendFormat": "{{net_dev_name}} - {{ifname}}"
    }
   ]
  },
  {
   "title": "Bandwidth | Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(rdma_tx_vport_rdma_unicast_bytes_total{pod_name!=\"\", pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[$__rate_interval]) + rate(rdma_tx_vport_rdma_multicast_bytes_total{pod_name!=\"\", pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[$__rate_interval]) ",
     "legendFormat": "{{net_dev_name}} - {{ifname}}"
    }
   ]
  },
  {
   "title": "Rate of Bandwidth | Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(rate(rdma_rx_vport_rdma_unicast_bytes_total{pod_name!=\"\", pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[$__rate_interval]) +\n  rate(rdma_rx_vport_rdma_multicast_bytes_total{pod_name!=\"\", pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[$__rate_interval])\n)\n/\n(rdma_vport_speed_mbps_total{pod_name!=\"\"} * 1000000 / 8) * 100",
     "legendFormat": "{{net_dev_name}} - {{ifname}}"
    }
   ]
  },
  {
   "title": "Rate of Bandwidth | Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(rate(rdma_tx_vport_rdma_unicast_bytes_total{pod_name!=\"\", pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[$__rate_interval]) +\n  rate(rdma_tx_vport_rdma_multicast_bytes_total{pod_name!=\"\", pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[$__rate_interval])\n)\n/\n(rdma_vport_speed_mbps_total{pod_name!=\"\"} * 1000000 / 8) * 100",
     "legendFormat": "{{net_dev_name}} - {{ifname}}"
    }
   ]
  },
  {
   "title": "rdma_read_unicast_packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(rdma_rx_vport_rdma_unicast_packets_total{pod_name!=\"\", pod_namespace!=\"\", pod_name=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{net_dev_name}} - {{ifname}}"
    }
   ]
  },
  {
   "title": "rdma_read_multicast_packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "targets": [
    {
     "expr": "rate(rdma_rx_vport_rdma_multicast_packets_total{pod_name!=\"\", pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{net_dev_name}} - {{ifname}}"
    }
   ]
  },
  {
   "title": "read_rdma_multicast_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(rdma_rx_vport_rdma_multicast_bytes_total{pod_name!=\"\", pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{net_dev_name}} - {{ifname}}"
    }
   ]
  },
  {
   "title": "rdma_rx_read_requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "targets": [
    {
     "expr": "rate(rdma_rx_read_requests_total{pod_name!=\"\", pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{net_dev_name}} - {{ifname}}"
    }
   ]
  },
  {
   "title": "rdma_write_unicast_packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(rdma_tx_vport_rdma_unicast_packets_total{pod_name!=\"\", pod_namespace!=\"\", pod_name=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{net_dev_name}} - {{ifname}}"
    }
   ]
  },
  {
   "title": "rdma_write_multicast_packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
   "targets": [
    {
     "expr": "irate(rdma_tx_vport_rdma_multicast_packets_total{pod_namespace!=\"\", pod_name=~\"$pod\"}[1m])",
     "legendFormat": "{{net_dev_name}} - {{ifname}}"
    }
   ]
  },
  {
   "title": "write_rdma_multicast",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "rate(rdma_tx_vport_rdma_multicast_bytes_total{pod_name!=\"\", pod_name=~\"$pod\"}[1m]) * 8 / 1000000",
     "legendFormat": "{{net_dev_name}} - {{ifname}}"
    }
   ]
  },
  {
   "title": "rdma_rx_write_requests",
   "type": "timeseries",
   "description": "Number of received WRITE requests for the associated Queue Pairs",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(rdma_rx_write_requests_total{pod_name!=\"\", pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{net_dev_name}} - {{ifname}}"
    }
   ]
  },
  {
   "title": "req  cqe error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(rdma_req_cqe_error_total{pod_name!=\"\", pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{net_dev_name}} - {{ifname}}"
    }
   ]
  },
  {
   "title": "duplicate request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
   "targets": [
    {
     "expr": "irate(rdma_duplicate_request_total{pod_namespace!=\"\", pod_name=~\"$pod\"}[1m])",
     "legendFormat": "{{net_dev_name}} - {{ifname}}"
    }
   ]
  },
  {
   "title": "rdma_resp_remote_access_errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "rate(rdma_resp_remote_access_errors_total{pod_name!=\"\", pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{net_dev_name}} - {{ifname}}"
    }
   ]
  },
  {
   "title": "rdma_req_remote_access_errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 33 },
   "targets": [
    {
     "expr": "rate(rdma_req_remote_access_errors_total{pod_name!=\"\", pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{net_dev_name}} - {{ifname}}"
    }
   ]
  },
  {
   "title": "rdma_rx_dct_connect",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "rate(rdma_rx_dct_connect_total{pod_name!=\"\", pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{net_dev_name}} - {{ifname}}"
    }
   ]
  },
  {
   "title": "rdma_rx_atomic_requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 41 },
   "targets": [
    {
     "expr": "rate(rdma_rx_atomic_requests_total{pod_name!=\"\", pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{net_dev_name}} - {{ifname}}"
    }
   ]
  },
  {
   "title": "rdma_req_remote_invalid_request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "rate(rdma_req_remote_invalid_request_total{pod_name!=\"\", pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{net_dev_name}} - {{ifname}}"
    }
   ]
  },
  {
   "title": "rdma_duplicate_request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 41 },
   "targets": [
    {
     "expr": "rate(rdma_duplicate_request_total{pod_namespace!=\"\",pod_name=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{net_dev_name}} - {{ifname}}"
    }
   ]
  },
  {
   "title": "rdma_rx_atomic_requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "rate(rdma_rx_atomic_requests_total{pod_name!=\"\", pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{net_dev_name}} - {{ifname}}"
    }
   ]
  },
  {
   "title": "rdma_resp_cqe_flush_error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 49 },
   "targets": [
    {
     "expr": "rate(rdma_resp_cqe_flush_error_total{pod_name!=\"\", pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{net_dev_name}} - {{ifname}}"
    }
   ]
  },
  {
   "title": "rdma_req_cqe_flush_error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "rate(rdma_req_cqe_flush_error_total{pod_name!=\"\", pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{net_dev_name}} - {{ifname}}"
    }
   ]
  },
  {
   "title": "rdma_resp_cqe_error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 49 },
   "targets": [
    {
     "expr": "rate(rdma_resp_cqe_error_total{pod_name!=\"\", pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{net_dev_name}} - {{ifname}}"
    }
   ]
  },
  {
   "title": "rdma_rnr_nak_retry_err",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "rate(rdma_rnr_nak_retry_err_total{pod_name!=\"\", pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{net_dev_name}} - {{ifname}}"
    }
   ]
  },
  {
   "title": "rdma_out_of_sequence",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 57 },
   "targets": [
    {
     "expr": "rate(rdma_out_of_sequence_total{pod_name!=\"\", pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{net_dev_name}} - {{ifname}}"
    }
   ]
  },
  {
   "title": "rdma_packet_seq_err",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "rate(rdma_packet_seq_err_total{pod_name!=\"\", pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{net_dev_name}} - {{ifname}}"
    }
   ]
  },
  {
   "title": "rdma_resp_local_length_error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 57 },
   "targets": [
    {
     "expr": "rate(rdma_resp_local_length_error_total{pod_name!=\"\", pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{net_dev_name}} - {{ifname}}"
    }
   ]
  },
  {
   "title": "rdma_implied_nak_seq_err",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "rate(rdma_implied_nak_seq_err_total{pod_name!=\"\", pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{net_dev_name}} - {{ifname}}"
    }
   ]
  },
  {
   "title": "rdma_local_ack_timeout_err",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 65 },
   "targets": [
    {
     "expr": "rate(rdma_local_ack_timeout_err_total{pod_name!=\"\", pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{net_dev_name}} - {{ifname}}"
    }
   ]
  },
  {
   "title": "rdma_out_of_buffer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "rate(rdma_out_of_buffer_total{pod_name!=\"\", pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{net_dev_name}} - {{ifname}}"
    }
   ]
  },
  {
   "title": "rdma_req_cqe_error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 65 },
   "targets": [
    {
     "expr": "rate(rdma_req_cqe_error_total{pod_name!=\"\", pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{net_dev_name}} - {{ifname}}"
    }
   ]
  },
  {
   "title": "rdma_np_cnp_sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "rate(rdma_np_cnp_sent_total{pod_name!=\"\", pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{net_dev_name}} - {{ifname}}"
    }
   ]
  },
  {
   "title": "rdma_roce_adp_retrans_to",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 73 },
   "targets": [
    {
     "expr": "rate(rdma_roce_adp_retrans_to_total{pod_name!=\"\", pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{net_dev_name}} - {{ifname}}"
    }
   ]
  },
  {
   "title": "rdma_roce_slow_restart_cnps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 73 },
   "targets": [
    {
     "expr": "rate(rdma_roce_slow_restart_cnps_total{pod_name!=\"\", pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{ifname}} - {{pod_namespace}}/{{pod_name}}"
    }
   ]
  },
  {
   "title": "rdma_np_ecn_marked_roce_packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 73 },
   "targets": [
    {
     "expr": "rate(rdma_np_ecn_marked_roce_packets_total{pod_name!=\"\", pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{net_dev_name}} - {{ifname}}"
    }
   ]
  },
  {
   "title": "rdma_rp_cnp_handled",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "rate(rdma_rp_cnp_handled_total{pod_name!=\"\", pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{net_dev_name}} - {{ifname}}"
    }
   ]
  },
  {
   "title": "rdma_roce_slow_restart",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 81 },
   "targets": [
    {
     "expr": "rate(rdma_roce_slow_restart_total{pod_name!=\"\", pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{ifname}} - {{pod_namespace}}/{{pod_name}}"
    }
   ]
  },
  {
   "title": "rdma_rp_cnp_ignored",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 81 },
   "targets": [
    {
     "expr": "rate(rdma_rp_cnp_ignored_total{pod_name!=\"\", pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{net_dev_name}} - {{ifname}}"
    }
   ]
  },
  {
   "title": "rdma_roce_adp_retrans",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 81 },
   "targets": [
    {
     "expr": "rate(rdma_roce_adp_retrans_total{pod_name!=\"\", pod_namespace=~\"$namespace\", pod_name=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{ifname}} - {{pod_namespace}}/{{pod_name}}"
    }
   ]
  }
 ]
}