{
 "title": "Spiderpool RDMA | Cluster",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of RDMA-Capable Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(rdma_tx_vport_rdma_unicast_bytes_total{pod_name!=\"\"}) by (node_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RDMA Pod Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(rdma_tx_vport_rdma_unicast_bytes_total{pod_name!=\"\"}) by (pod_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Bandwidth | Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n  rate(rdma_rx_vport_rdma_unicast_bytes_total{is_root=\"true\"}[5m]) +\n  rate(rdma_rx_vport_rdma_multicast_bytes_total{is_root=\"true\"}[5m])\n)",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Cluster Bandwidth  | Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n  rate(rdma_tx_vport_rdma_unicast_bytes_total{is_root=\"true\"}[5m]) +\n  rate(rdma_tx_vport_rdma_multicast_bytes_total{is_root=\"true\"}[5m])\n)",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Node Bandwidth | Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (node_name) (\n  rate(rdma_rx_vport_rdma_unicast_bytes_total[5m]) +\n  rate(rdma_rx_vport_rdma_multicast_bytes_total[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Bandwidth  | Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (node_name) (\n  rate(rdma_tx_vport_rdma_unicast_bytes_total[5m]) +\n  rate(rdma_tx_vport_rdma_multicast_bytes_total[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Bandwidth | Node | Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (node_name) (\n  rate(rdma_rx_vport_rdma_unicast_bytes_total{}[3m]) + rate(rdma_rx_vport_rdma_multicast_bytes_total[3m])\n)\n/ sum by (node_name) (rdma_vport_speed_mbps_total{is_root=\"true\"} * 1000000 / 8) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Bandwidth | Node | Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (node_name) (\n  rate(rdma_tx_vport_rdma_unicast_bytes_total{}[3m]) + rate(rdma_tx_vport_rdma_multicast_bytes_total[3m])\n)\n/ sum by (node_name) (rdma_vport_speed_mbps_total{is_root=\"true\"} * 1000000 / 8) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Top traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Node Top 10 | Bandwidth | Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(\n  10,\n  sum by (node_name) (\n    rate(rdma_rx_vport_rdma_unicast_bytes_total[5m]) +\n    rate(rdma_rx_vport_rdma_multicast_bytes_total[5m])\n  )\n)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Node Top 10 | Bandwidth | Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(\n  10,\n  sum by (node_name) (\n    rate(rdma_tx_vport_rdma_unicast_bytes_total[5m]) +\n    rate(rdma_tx_vport_rdma_multicast_bytes_total[5m])\n  )\n)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Node Top 10 | Rate of Bandwidth  | Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(\n  10,\nsum by (node_name) (\n  rate(rdma_rx_vport_rdma_unicast_bytes_total{}[3m]) + rate(rdma_rx_vport_rdma_multicast_bytes_total[3m])\n)\n/ sum by (node_name) (rdma_vport_speed_mbps_total{is_root=\"true\"} * 1000000 / 8) * 100\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Top 10 | Rate of Bandwidth | Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(\n  10,\nsum by (node_name) (\n  rate(rdma_tx_vport_rdma_unicast_bytes_total{}[3m]) + rate(rdma_tx_vport_rdma_multicast_bytes_total[3m])\n)\n/ sum by (node_name) (rdma_vport_speed_mbps_total{is_root=\"true\"} * 1000000 / 8) * 100\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Top 10 | Bandwidth | Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(\n  10,\n  sum by (pod_name) (\n    (\n      rate(rdma_rx_vport_rdma_unicast_bytes_total{pod_name!=\"\"}[5m]) +\n      rate(rdma_rx_vport_rdma_multicast_bytes_total{pod_name!=\"\"}[5m])\n    )\n  )\n)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Pod Top 10 | Bandwidth | Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(\n  10,\n  sum by (pod_name) (\n    (\n      rate(rdma_tx_vport_rdma_unicast_bytes_total{pod_name!=\"\"}[5m]) +\n      rate(rdma_tx_vport_rdma_multicast_bytes_total{pod_name!=\"\"}[5m])\n    )\n  )\n)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Workload Top 10 | Bandwidth | Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(\n  10,\n  sum by (owner_kind,owner_namespace,owner_name) (\n    (\n      rate(rdma_rx_vport_rdma_unicast_bytes_total{pod_name!=\"\"}[5m]) +\n      rate(rdma_rx_vport_rdma_multicast_bytes_total{pod_name!=\"\"}[5m])\n    )\n  )\n)",
     "legendFormat": "{{owner_kind}} - {{owner_namespace}}/{{owner_name}}"
    }
   ]
  },
  {
   "title": "Workload Top 10 | Bandwidth | Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(\n  10,\n  sum by (owner_kind,owner_namespace,owner_name) (\n    (\n      rate(rdma_tx_vport_rdma_unicast_bytes_total{pod_name!=\"\"}[5m]) +\n      rate(rdma_tx_vport_rdma_multicast_bytes_total{pod_name!=\"\"}[5m])\n    )\n  )\n)",
     "legendFormat": "{{owner_kind}} - {{owner_namespace}}/{{owner_name}}"
    }
   ]
  }
 ]
}