{{- if and .Values.sriov.install .Values.sriov.operatorConfig.enableOperatorWebhook -}}
{{- if eq .Values.sriov.webhooktls.method "certmanager" -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.sriov.name | trunc 63 | trimSuffix "-" }}-webhook-server-certs
  namespace: {{ .Release.Namespace }}
spec:
  issuerRef:
    name: {{ .Values.sriov.webhooktls.certmanager.issuerName | trunc 63 | trimSuffix "-" }}
  secretName: {{ .Values.sriov.webhooktls.secretName | trunc 63 | trimSuffix "-" }}
  commonName: {{ .Values.sriov.name | trunc 63 | trimSuffix "-" }}.{{ .Release.Namespace }}.svc
  dnsNames:
    - {{ .Values.sriov.webhooktls.serviceName | trunc 63 | trimSuffix "-" }}
    - {{ .Values.sriov.webhooktls.serviceName | trunc 63 | trimSuffix "-" }}.{{ .Release.Namespace }}
    - {{ .Values.sriov.webhooktls.serviceName | trunc 63 | trimSuffix "-" }}.{{ .Release.Namespace }}.svc
    - {{ .Values.sriov.webhooktls.serviceName | trunc 63 | trimSuffix "-" }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDnsDomain }}
  {{- range $dns := .Values.sriov.webhooktls.certmanager.extraDnsNames }}
  - {{ $dns | quote }}
  {{- end }}
  {{- if .Values.sriov.webhooktls.certmanager.extraIPAddresses }}
  ipAddresses:
  {{- range $ip := .Values.sriov.webhooktls.certmanager.extraIPAddresses }}
  - {{ $ip | quote }}
  {{- end }}
  {{- end }}
  duration: {{ printf "%dh" (mul .Values.sriov.webhooktls.certmanager.certValidityDuration 24) }}
  {{- end }}
{{- if (eq .Values.sriov.webhooktls.method "provided") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.sriov.webhooktls.secretName | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  ca.crt:  {{ .Values.sriov.webhooktls.provided.tlsCa | required "missing sriov.webhooktls.provided.tlsCa" }}
  tls.crt: {{ .Values.sriov.webhooktls.provided.tlsCert | required "missing sriov.webhooktls.provided.tlsCert" }}
  tls.key: {{ .Values.sriov.webhooktls.provided.tlsKey  | required "missing sriov.webhooktls.provided.tlsKey"  }}
  {{- end }}
{{- if eq .Values.sriov.webhooktls.method "auto" }}
---
{{- $_ := include "generate-ca-certs" . }}
{{- $cn := printf .Values.sriov.name }}
{{- $ip := .Values.sriov.webhooktls.auto.extraIpAddresses }}
{{- $dns1 := printf "%s.%s" .Values.sriov.webhooktls.serviceName .Release.Namespace }}
{{- $dns2 := printf "%s.%s.svc" .Values.sriov.webhooktls.serviceName .Release.Namespace }}
{{- $dns3 := printf "%s.%s.svc.%s" .Values.sriov.webhooktls.serviceName .Release.Namespace .Values.global.clusterDnsDomain }}
{{- $dns := prepend .Values.sriov.webhooktls.auto.extraDnsNames $dns1 }}
{{- $dns = prepend $dns $dns2 }}
{{- $dns = prepend $dns $dns3 }}
{{- $dns = prepend $dns $cn }}
{{- $cert := genSignedCert $cn $ip $dns (.Values.sriov.webhooktls.auto.certExpiration | int) .ca }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.sriov.webhooktls.secretName | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  ca.crt:  {{ .ca.Cert | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key  | b64enc }}
{{- end }}
{{- end }}