{{- if eq .Values.sriov.injectortls.method "certmanager" -}}
{{- $_ := include "generate-ca-certs" . }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.sriov.name | trunc 63 | trimSuffix "-" }}-server-certs
  namespace: {{ .Release.Namespace }}
spec:
  issuerRef:
    name: {{ .Values.sriov.injectortls.certmanager.issuerName | trunc 63 | trimSuffix "-" }}
  secretName: {{ .Values.sriov.injectortls.secretName | trunc 63 | trimSuffix "-" }}
  commonName: {{ .Values.sriov.name | trunc 63 | trimSuffix "-" }}.{{ .Release.Namespace }}.svc
  dnsNames:
    - {{ .Values.sriov.name | trunc 63 | trimSuffix "-" }}
    - {{ .Values.sriov.name | trunc 63 | trimSuffix "-" }}.{{ .Release.Namespace }}
    - {{ .Values.sriov.name | trunc 63 | trimSuffix "-" }}.{{ .Release.Namespace }}.svc
    - {{ .Values.sriov.name | trunc 63 | trimSuffix "-" }}.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDnsDomain }}
  {{- range $dns := .Values.sriov.injectortls.certmanager.extraDnsNames }}
  - {{ $dns | quote }}
  {{- end }}
  {{- if .Values.sriov.injectortls.certmanager.extraIPAddresses }}
  ipAddresses:
  {{- range $ip := .Values.sriov.injectortls.certmanager.extraIPAddresses }}
  - {{ $ip | quote }}
  {{- end }}
  {{- end }}
  duration: {{ printf "%dh" (mul .Values.sriov.injectortls.certmanager.certValidityDuration 24) }}
  {{- end }}
{{- if (eq .Values.sriov.injectortls.method "provided") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.sriov.injectortls.secretName | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  ca.crt:  {{ .Values.sriov.injectortls.provided.tlsCa | required "missing sriov.injectortls.provided.tlsCa" }}
  tls.crt: {{ .Values.sriov.injectortls.provided.tlsCert | required "missing sriov.injectortls.provided.tlsCert" }}
  tls.key: {{ .Values.sriov.injectortls.provided.tlsKey  | required "missing sriov.injectortls.provided.tlsKey"  }}
  {{- end }}
{{- if eq .Values.sriov.injectortls.method "auto" }}
---
{{- $cn := printf "spidernet.io" }}
  {{- $ip := .Values.sriov.injectortls.auto.extraIpAddresses }}
  {{- $dns1 := printf "%s.%s" .Values.sriov.name .Release.Namespace }}
  {{- $dns2 := printf "%s.%s.svc" .Values.sriov.name .Release.Namespace }}
  {{- $dns3 := printf "%s.%s.svc.%s" .Values.sriov.name .Release.Namespace .Values.global.clusterDnsDomain }}
  {{- $dns := prepend .Values.sriov.injectortls.auto.extraDnsNames $dns1 }}
  {{- $dns = prepend $dns $dns2 }}
  {{- $dns = prepend $dns $dns3 }}
  {{- $dns = prepend $dns $cn }}
  {{- $cert := genSignedCert $cn $ip $dns (.Values.sriov.injectortls.auto.certExpiration | int) .ca }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.sriov.injectortls.secretName | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  ca.crt:  {{ .ca.Cert | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key  | b64enc }}
{{- end }}