- name: pr/release/bug
  description: bug pr in a new release
  color: d73a4a
- name: pr/release/feature-new
  description: new feature pr in a new release
  color: 0075ca
- name: pr/release/feature-changed
  description: changed feature pr in a new release
  color: cfd3d7
- name: pr/release/doc
  description: doc pr in a new release
  color: 0fd3d7
- name: pr/release/robot_update_githubpage
  description: auto robot update github page
  color: afd3d7
- name: pr/release/changelog
  description: manual changelog pr in a new release
  color: bfd3d7
- name: pr/release/chart
  description: manual chart pr in a new release
  color: bfd3d7
- name: pr/release/none-required
  description: not show up in a new release
  color: cfc3d7
- name: pr/approved
  description: This pull request could be merged
  color: dfd3d7
- name: pr/stale
  description: This pull is inactive
  color: dfd6d7
- name: pr/ready-review
  description: This pull is ready for review
  color: dfd6d7
- name: pr/dependabot/docker
  description: This pull is for dockerfile from dependabot
  color: dfd6d7
- name: pr/dependabot/gomod
  description: This pull is for gomod from dependabot
  color: dfd6d7
- name: pr/dependabot/github-actions
  description: This pull is for github-actions from dependabot
  color: dfd6d7
- name: pr/need-release-label
  description: This pull neel release label for merge
  color: df56d7
- name: issue/bug
  description: bug
  color: efd3d7
- name: issue/not-assign
  description: a new issue not assigned
  color: ffd3d7
- name: issue/ci-fail
  description: ci failed
  color: 0ad3d7
- name: issue/doc
  description: documentation is wrong or missing
  color: 0bd3d7
- name: issue/feature
  description: want new feature
  color: 0cd3d7
- name: issue/usage
  description: no idea about usage
  color: 0dd3d7
- name: issue/duplicate
  description: This issue request already exists
  color: 0fd3d7
- name: issue/ignore
  description: This issue or pull request will ignore
  color: 15d3d7
- name: issue/stale
  description: This issue is inactive
  color: d0d6d7
