# rules https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md
# example https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml
# example https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.jsonc

# Default state for all rules
default: true

# Multiple consecutive blank lines
MD012: false

# Line length
MD013: false

# Multiple headings with the same content
MD024: false

# Fenced code blocks should have a language specified
MD040: false

# Dollar signs used before commands without showing output
MD014: false

# Inline HTML
MD033: false

# no-trailing-spaces Trailing spaces
MD009: false
