# Default values for spiderpool.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

ipFamily:
  enableIPv4: true
  enableIPv6: true

rbac:
  # -- Enable creation of Resource-Based Access Control configuration.
  create: true

# default spiderpool
nameOverride: ""

clusterDnsDomain: "cluster.local"

## @param commonAnnotations Annotations to add to all deployed objects
##
commonAnnotations: {}
#  annotation1: v1
#  annotation2: v2

## @param commonLabels Labels to add to all deployed objects
##
commonLabels: {}
#  label1: v1
#  labele: v2

ipamPlugin:
  # -- Configure the path to the configuration directory on the host.
  confPath: /etc/cni/net.d/spiderpool
  binPath: /opt/cni/bin

  # -- Configure the path to the binary directory on the host.
  ipamBinPath: /opt/cni/bin

  # -- Configure the unix socket path to connect with the spiderpool agent.
  ipamUNIXSocketDir: /var/run/spidernet
  ipamUNIXSocketPath: /var/run/spidernet/spiderpool.sock

clusterDefaultPool:
  installIPv4IPPool: false
  installIPv6IPPool: false
  ipv4IPPoolName: "default-v4-ippool"
  ipv6IPPoolName: "default-v6-ippool"
  ipv4Subnet: ""
  ipv6Subnet: ""
  ipv4IPRanges: []
  ipv6IPRanges: []

configmap:
  configCmName: "spiderpool-conf"

  config:
    # -- Unix domain socket path to listen for ipam plugin.
    ipamUnixSocketPath: /var/run/spidernet/spiderpool.sock
    networkMode: legacy
    enableStatefulSet: true

spiderpoolAgent:
  name: "spiderpool-agent"

  binName: "spiderpool-agent"

  image:
    repository: ghcr.io/spidernet-io/spiderpool/spiderpool-agent
    pullPolicy: IfNotPresent
    # take preference over tag
    digest: ""
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
    imagePullSecrets: []
    # - name: "image-pull-secret"

  nodeSelector:
    kubernetes.io/os: linux

  nameOverride: ""

  serviceAccount:
    create: true
    annotations: {}

  # -- http Port to listen to for health checking
  healthPort: 5710

  updateStrategy:
    rollingUpdate:
      maxUnavailable: 2
    type: RollingUpdate

  service:
    # Optional annotations to add to the Service
    annotations: {}
    type: ClusterIP

  # --  Node tolerations
  # ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/disk-pressure
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/memory-pressure
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/pid-pressure
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/unschedulable
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/network-unavailable
      operator: Exists
    - key: node.kubernetes.io/not-ready
      effect: NoSchedule
    - key: node-role.kubernetes.io/master
      effect: NoSchedule
    - key: node-role.kubernetes.io/control-plane
      effect: NoSchedule
    - key: CriticalAddonsOnly
      operator: Exists

  priorityClassName: ""

  affinity: {}

  # -- Additional container arguments.
  extraArgs: []

  # -- Additional container environment variables.
  extraEnv: []

  # -- Additional agent hostPath mounts.
  extraHostPathMounts: []
    # - name: host-mnt-data
    #   mountPath: /host/mnt/data
    #   hostPath: /mnt/data
    #   hostPathType: Directory
    #   readOnly: true
    #   mountPropagation: HostToContainer

  # -- Additional agent volumes.
  extraVolumes: []

  # -- Additional agent volumeMounts.
  extraVolumeMounts: []

  # -- Annotations to be added to agent pods
  podAnnotations: {}

  # -- Labels to be added to agent pods
  podLabels: {}

  # -- Configure the path to where to mount the ConfigMap inside the agent pod.
  confFileMountPath: /tmp/cni-configuration

  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 128Mi

  # -- Security context to be added to agent pods
  securityContext: {}
  # runAsUser: 0

  # -- Configure the path to where the CNI configuration directory is mounted
  # inside the agent pod.
  hostConfDirMountPath: /host/etc/cni/net.d/spiderpool

  healthChecking:
    startupProbe:
      # -- failure threshold of startup probe.
      # 105 x 2s translates to the old behaviour of the readiness probe (120s delay + 30 x 3s)
      failureThreshold: 60
      # -- interval between checks of the startup probe
      periodSeconds: 2

    livenessProbe:
      # -- failure threshold of liveness probe
      failureThreshold: 6
      # -- interval between checks of the liveness probe
      periodSeconds: 10

    readinessProbe:
      # -- failure threshold of readiness probe
      failureThreshold: 3
      # -- interval between checks of the readiness probe
      periodSeconds: 10

  # -- Enable prometheus metrics for cilium-operator on the configured port at
  # /metrics
  prometheus:
    # -- Enable service monitors.
    # This requires the prometheus CRDs to be available (see https://github.com/prometheus-operator/prometheus-operator/blob/master/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml)
    enabled: false
    port: 5711
    serviceMonitor:
      labels: {}
      annotations: {}
    prometheusRule:
      # enable alter rules
      enabled: false

  debug:
    # debug, info, warn, error, fatal, panic
    logLevel: "info"
    gopsPort: 5712

spiderpoolController:
  name: "spiderpool-controller"

  replicas: 1

  binName: "spiderpool-controller"

  # ippool is not installed when installation , so have to be hostnetwork
  hostnetwork: true

  nameOverride: ""

  image:
    repository: ghcr.io/spidernet-io/spiderpool/spiderpool-controller
    pullPolicy: IfNotPresent
    # take preference over tag
    digest: ""
    # digest: "sha256:251ff274acf22fd2067b29a31e9fda94253d2961c061577203621583d7e85bd2"
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
    imagePullSecrets: []
    # - name: "image-pull-secret"

  nodeSelector:
    kubernetes.io/os: linux

  affinity: {}

  serviceAccount:
    create: true
    name: ""
    annotations: {}

  service:
    # Optional annotations to add to the Service
    annotations: {}
    type: ClusterIP

  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/disk-pressure
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/memory-pressure
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/pid-pressure
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/unschedulable
      operator: Exists
    - effect: NoSchedule
      key: node.kubernetes.io/network-unavailable
      operator: Exists
    - key: node.kubernetes.io/not-ready
      effect: NoSchedule
    - key: node-role.kubernetes.io/master
      effect: NoSchedule
    - key: node-role.kubernetes.io/control-plane
      effect: NoSchedule
    - key: CriticalAddonsOnly
      operator: Exists

  priorityClassName: ""

  # -- Additional container arguments.
  extraArgs: []

  # -- Additional container environment variables.
  extraEnv: []

  # -- Additional agent hostPath mounts.
  extraHostPathMounts: []
    # - name: host-mnt-data
    #   mountPath: /host/mnt/data
    #   hostPath: /mnt/data
    #   hostPathType: Directory
    #   readOnly: true
  #   mountPropagation: HostToContainer

  # -- Additional agent volumes.
  extraVolumes: []
    # - name: test-val
    #   mountPath: /host/tmp

  # -- Additional agent volumeMounts.
  extraVolumeMounts: []
    # - name: test-val
    #   mountPath: /tmp

  # -- Annotations to be added to agent pods
  podAnnotations: {}
    # test: 100

  # -- Labels to be added to agent pods
  podLabels: {}

  # -- security context
  securityContext: {}
  # runAsUser: 0

  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 128Mi

  # PodDisruptionBudget settings
  podDisruptionBudget:
    # -- enable PodDisruptionBudget
    # ref: https://kubernetes.io/docs/concepts/workloads/pods/disruptions/
    enabled: false
    # -- Minimum number/percentage of pods that should remain scheduled.
    # When it's set, maxUnavailable must be disabled by `maxUnavailable: null`
    minAvailable: 1
    # -- Maximum number/percentage of pods that may be made unavailable
   # maxUnavailable: 1

  healthChecking:
    startupProbe:
      # -- failure threshold of startup probe.
      # 105 x 2s translates to the old behaviour of the readiness probe (120s delay + 30 x 3s)
      failureThreshold: 30
      # -- interval between checks of the startup probe
      periodSeconds: 2

    livenessProbe:
      # -- failure threshold of liveness probe
      failureThreshold: 6
      # -- interval between checks of the liveness probe
      periodSeconds: 10

    readinessProbe:
      # -- failure threshold of readiness probe
      failureThreshold: 3
      # -- interval between checks of the readiness probe
      periodSeconds: 10

  # -- http Port to listen to for health checking
  healthPort: 5720

  # -- https Port to listen to webhook
  webhookPort: 5722

  # -- https Port to listen to cli command
  cliPort: 5723

  # -- Enable prometheus metrics for cilium-operator on the configured port at
  # /metrics
  prometheus:
    enabled: false
    port: 5721
    serviceMonitor:
      # -- Enable service monitors.
      # This requires the prometheus CRDs to be available (see https://github.com/prometheus-operator/prometheus-operator/blob/master/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml)
      enabled: false
      labels: {}
      annotations: {}
    prometheusRule:
      # enable alter rules
      enabled: false

  debug:
    # debug, info, warn, error, fatal, panic
    logLevel: "info"
    gopsPort: 5724

  gc:
    # global enable
    enabled: true
    # if enabled=false, ignore this
    gcTerminatingPodIPEnabled: true
    # delay to gc pod ip after pod graceful time, second
    gcTerminatingPodIPDelay: 0
    # if enabled=false, ignore this
    gcEvictedPodIPEnabled: true
    # delay to gc pod ip after pod graceful time, second
    gcEvictedPodIPDelay: 0

  # -- TLS configuration for webhook
  tls:
    # -- Set the method to auto-generate certificates. Supported values:
    # - provided:     provide all certificates by helm options
    # - certmanager:  This method use cert-manager to generate & rotate certificates.
    method: provided

    # the secret with same namespace
    secretName: "spiderpool-controller-server-certs"

    # for certmanager method
    certmanager:
      # -- Generated certificates validity duration in days.
      certValidityDuration: 365

      # If not specified, a CA issuer will be created.
      # used by method certmanager
      issuerName: ""

      # -- Extra DNS names added to certificate when it's auto generated
      extraDnsNames: []
      # -- Extra IP addresses added to certificate when it's auto generated
      extraIPAddresses: []

    # -- for provided method
    server:
      # used by method provided
      # encoded
      tlsCert: ""
      tlsKey: ""
      tlsCa: ""
