version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - errorlint

  settings:
    errcheck:
      # To disable the errcheck built-in exclude list.
      # See `-excludeonly` option in https://github.com/kisielk/errcheck#excluding-functions for details.
      # Default: false
      disable-default-exclusions: true

    staticcheck:
      checks:
        # Default checks https://golangci-lint.run/usage/linters/#staticcheck
        - all
        - -ST1000
        - -ST1003
        - -ST1006
        - -ST1016
        - -ST1020
        - -ST1021
        - -ST1022
        - -ST1005
        - -ST1008
        - -ST1019
        - -QF1001
        - -QF1002
        - -QF1003
        - -QF1006
        - -QF1007
        - -QF1008
        - -QF1012
      dot-import-whitelist:
        - "github.com/onsi/ginkgo/v2"
        - "github.com/onsi/gomega"
        - "fmt"

formatters:
  enable:
    - gofmt
    - gofumpt
