coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 10%
        if_ci_failed: error
    patch:
      default:
        target: 60%
        threshold: 10%
        if_ci_failed: ignore

comment:
  layout: "reach, diff, flags, files"
  behavior: default
