apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-affinity-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-affinity-deploy
  template:
    metadata:
      annotations:
        ipam.spidernet.io/ippool: |-
          {
            "ipv4": ["master-ipv4-ippool", "worker-ipv4-ippool"]
          }
      labels:
        app: node-affinity-deploy
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: node-affinity-deploy
              topologyKey: kubernetes.io/hostname
      containers:
        - name: node-affinity-deploy
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c", "trap : TERM INT; sleep infinity & wait"]
