// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package daemonset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteIpamIpsReader is a Reader for the DeleteIpamIps structure.
type DeleteIpamIpsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteIpamIpsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteIpamIpsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewDeleteIpamIpsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteIpamIpsOK creates a DeleteIpamIpsOK with default headers values
func NewDeleteIpamIpsOK() *DeleteIpamIpsOK {
	return &DeleteIpamIpsOK{}
}

/*
DeleteIpamIpsOK describes a response with status code 200, with default header values.

Success
*/
type DeleteIpamIpsOK struct {
}

func (o *DeleteIpamIpsOK) Error() string {
	return fmt.Sprintf("[DELETE /ipam/ips][%d] deleteIpamIpsOK ", 200)
}

func (o *DeleteIpamIpsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteIpamIpsInternalServerError creates a DeleteIpamIpsInternalServerError with default headers values
func NewDeleteIpamIpsInternalServerError() *DeleteIpamIpsInternalServerError {
	return &DeleteIpamIpsInternalServerError{}
}

/*
DeleteIpamIpsInternalServerError describes a response with status code 500, with default header values.

Failed
*/
type DeleteIpamIpsInternalServerError struct {
}

func (o *DeleteIpamIpsInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /ipam/ips][%d] deleteIpamIpsInternalServerError ", 500)
}

func (o *DeleteIpamIpsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
