// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package daemonset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetWorkloadendpointReader is a Reader for the GetWorkloadendpoint structure.
type GetWorkloadendpointReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetWorkloadendpointReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetWorkloadendpointOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetWorkloadendpointInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetWorkloadendpointOK creates a GetWorkloadendpointOK with default headers values
func NewGetWorkloadendpointOK() *GetWorkloadendpointOK {
	return &GetWorkloadendpointOK{}
}

/*
GetWorkloadendpointOK describes a response with status code 200, with default header values.

Success
*/
type GetWorkloadendpointOK struct {
}

// IsSuccess returns true when this get workloadendpoint o k response has a 2xx status code
func (o *GetWorkloadendpointOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get workloadendpoint o k response has a 3xx status code
func (o *GetWorkloadendpointOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get workloadendpoint o k response has a 4xx status code
func (o *GetWorkloadendpointOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get workloadendpoint o k response has a 5xx status code
func (o *GetWorkloadendpointOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get workloadendpoint o k response a status code equal to that given
func (o *GetWorkloadendpointOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get workloadendpoint o k response
func (o *GetWorkloadendpointOK) Code() int {
	return 200
}

func (o *GetWorkloadendpointOK) Error() string {
	return fmt.Sprintf("[GET /workloadendpoint][%d] getWorkloadendpointOK ", 200)
}

func (o *GetWorkloadendpointOK) String() string {
	return fmt.Sprintf("[GET /workloadendpoint][%d] getWorkloadendpointOK ", 200)
}

func (o *GetWorkloadendpointOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetWorkloadendpointInternalServerError creates a GetWorkloadendpointInternalServerError with default headers values
func NewGetWorkloadendpointInternalServerError() *GetWorkloadendpointInternalServerError {
	return &GetWorkloadendpointInternalServerError{}
}

/*
GetWorkloadendpointInternalServerError describes a response with status code 500, with default header values.

Get workloadendpoint failure
*/
type GetWorkloadendpointInternalServerError struct {
}

// IsSuccess returns true when this get workloadendpoint internal server error response has a 2xx status code
func (o *GetWorkloadendpointInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get workloadendpoint internal server error response has a 3xx status code
func (o *GetWorkloadendpointInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get workloadendpoint internal server error response has a 4xx status code
func (o *GetWorkloadendpointInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get workloadendpoint internal server error response has a 5xx status code
func (o *GetWorkloadendpointInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get workloadendpoint internal server error response a status code equal to that given
func (o *GetWorkloadendpointInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get workloadendpoint internal server error response
func (o *GetWorkloadendpointInternalServerError) Code() int {
	return 500
}

func (o *GetWorkloadendpointInternalServerError) Error() string {
	return fmt.Sprintf("[GET /workloadendpoint][%d] getWorkloadendpointInternalServerError ", 500)
}

func (o *GetWorkloadendpointInternalServerError) String() string {
	return fmt.Sprintf("[GET /workloadendpoint][%d] getWorkloadendpointInternalServerError ", 500)
}

func (o *GetWorkloadendpointInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
