// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package daemonset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/spidernet-io/spiderpool/api/v1/agent/models"
)

// GetCoordinatorConfigReader is a Reader for the GetCoordinatorConfig structure.
type GetCoordinatorConfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetCoordinatorConfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetCoordinatorConfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetCoordinatorConfigFailure()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetCoordinatorConfigOK creates a GetCoordinatorConfigOK with default headers values
func NewGetCoordinatorConfigOK() *GetCoordinatorConfigOK {
	return &GetCoordinatorConfigOK{}
}

/*
GetCoordinatorConfigOK describes a response with status code 200, with default header values.

Success
*/
type GetCoordinatorConfigOK struct {
	Payload *models.CoordinatorConfig
}

// IsSuccess returns true when this get coordinator config o k response has a 2xx status code
func (o *GetCoordinatorConfigOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get coordinator config o k response has a 3xx status code
func (o *GetCoordinatorConfigOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get coordinator config o k response has a 4xx status code
func (o *GetCoordinatorConfigOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get coordinator config o k response has a 5xx status code
func (o *GetCoordinatorConfigOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get coordinator config o k response a status code equal to that given
func (o *GetCoordinatorConfigOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get coordinator config o k response
func (o *GetCoordinatorConfigOK) Code() int {
	return 200
}

func (o *GetCoordinatorConfigOK) Error() string {
	return fmt.Sprintf("[GET /coordinator/config][%d] getCoordinatorConfigOK  %+v", 200, o.Payload)
}

func (o *GetCoordinatorConfigOK) String() string {
	return fmt.Sprintf("[GET /coordinator/config][%d] getCoordinatorConfigOK  %+v", 200, o.Payload)
}

func (o *GetCoordinatorConfigOK) GetPayload() *models.CoordinatorConfig {
	return o.Payload
}

func (o *GetCoordinatorConfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CoordinatorConfig)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetCoordinatorConfigFailure creates a GetCoordinatorConfigFailure with default headers values
func NewGetCoordinatorConfigFailure() *GetCoordinatorConfigFailure {
	return &GetCoordinatorConfigFailure{}
}

/*
GetCoordinatorConfigFailure describes a response with status code 500, with default header values.

Config not initialized successfully or others
*/
type GetCoordinatorConfigFailure struct {
	Payload models.Error
}

// IsSuccess returns true when this get coordinator config failure response has a 2xx status code
func (o *GetCoordinatorConfigFailure) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get coordinator config failure response has a 3xx status code
func (o *GetCoordinatorConfigFailure) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get coordinator config failure response has a 4xx status code
func (o *GetCoordinatorConfigFailure) IsClientError() bool {
	return false
}

// IsServerError returns true when this get coordinator config failure response has a 5xx status code
func (o *GetCoordinatorConfigFailure) IsServerError() bool {
	return true
}

// IsCode returns true when this get coordinator config failure response a status code equal to that given
func (o *GetCoordinatorConfigFailure) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get coordinator config failure response
func (o *GetCoordinatorConfigFailure) Code() int {
	return 500
}

func (o *GetCoordinatorConfigFailure) Error() string {
	return fmt.Sprintf("[GET /coordinator/config][%d] getCoordinatorConfigFailure  %+v", 500, o.Payload)
}

func (o *GetCoordinatorConfigFailure) String() string {
	return fmt.Sprintf("[GET /coordinator/config][%d] getCoordinatorConfigFailure  %+v", 500, o.Payload)
}

func (o *GetCoordinatorConfigFailure) GetPayload() models.Error {
	return o.Payload
}

func (o *GetCoordinatorConfigFailure) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
