{{- if .Values.clusterDefaultPool.installIPv4IPPool }}
{{- if .Values.ipFamily.enableIPv4 }}
apiVersion: spiderpool.spidernet.io/v1
kind: IPPool
metadata:
  name: {{ .Values.clusterDefaultPool.ipv4IPPoolName | trunc 63 | trimSuffix "-" }}
spec:
  ipVersion: IPv4
  subnet: {{ .Values.clusterDefaultPool.ipv4Subnet }}
  disable: false
  ips:
  {{- range  .Values.clusterDefaultPool.ipv4IPRanges }}
  - {{ . }}
  {{- end }}
{{- end }}
{{- end }}
---
{{- if .Values.clusterDefaultPool.installIPv6IPPool }}
{{- if .Values.ipFamily.enableIPv6 }}
apiVersion: spiderpool.spidernet.io/v1
kind: IPPool
metadata:
  name: {{ .Values.clusterDefaultPool.ipv6IPPoolName | trunc 63 | trimSuffix "-" }}
spec:
  ipVersion: IPv6
  subnet: {{ .Values.clusterDefaultPool.ipv6Subnet }}
  disable: false
  ips:
  {{- range .Values.clusterDefaultPool.ipv6IPRanges }}
  - {{ . }}
  {{- end }}
{{- end }}
{{- end }}