{{- if .Values.spiderpoolController.podDisruptionBudget.enabled }}
apiVersion: {{ include "capabilities.policy.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.spiderpoolController.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.global.commonAnnotations }}
  annotations:
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
  labels:
    {{- include "spiderpool.spiderpoolController.labels" . | nindent 4 }}
    {{- if .Values.global.commonLabels }}
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  minAvailable: {{ .Values.spiderpoolController.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "spiderpool.spiderpoolController.selectorLabels" . | nindent 6 }}
{{- end }}
