// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v2beta1 "github.com/spidernet-io/spiderpool/pkg/k8s/apis/spiderpool.spidernet.io/v2beta1"
	spiderpoolspidernetiov2beta1 "github.com/spidernet-io/spiderpool/pkg/k8s/client/clientset/versioned/typed/spiderpool.spidernet.io/v2beta1"
	gentype "k8s.io/client-go/gentype"
)

// fakeSpiderCNIConfigs implements SpiderCNIConfigInterface
type fakeSpiderCNIConfigs struct {
	*gentype.FakeClientWithList[*v2beta1.SpiderCNIConfig, *v2beta1.SpiderCNIConfigList]
	Fake *FakeSpiderpoolV2beta1
}

func newFakeSpiderCNIConfigs(fake *FakeSpiderpoolV2beta1, namespace string) spiderpoolspidernetiov2beta1.SpiderCNIConfigInterface {
	return &fakeSpiderCNIConfigs{
		gentype.NewFakeClientWithList[*v2beta1.SpiderCNIConfig, *v2beta1.SpiderCNIConfigList](
			fake.Fake,
			namespace,
			v2beta1.SchemeGroupVersion.WithResource("spidercniconfigs"),
			v2beta1.SchemeGroupVersion.WithKind("SpiderCNIConfig"),
			func() *v2beta1.SpiderCNIConfig { return &v2beta1.SpiderCNIConfig{} },
			func() *v2beta1.SpiderCNIConfigList { return &v2beta1.SpiderCNIConfigList{} },
			func(dst, src *v2beta1.SpiderCNIConfigList) { dst.ListMeta = src.ListMeta },
			func(list *v2beta1.SpiderCNIConfigList) []*v2beta1.SpiderCNIConfig {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v2beta1.SpiderCNIConfigList, items []*v2beta1.SpiderCNIConfig) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
