// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v2beta1 "github.com/spidernet-io/spiderpool/pkg/k8s/apis/spiderpool.spidernet.io/v2beta1"
	spiderpoolspidernetiov2beta1 "github.com/spidernet-io/spiderpool/pkg/k8s/client/clientset/versioned/typed/spiderpool.spidernet.io/v2beta1"
	gentype "k8s.io/client-go/gentype"
)

// fakeSpiderMultusConfigs implements SpiderMultusConfigInterface
type fakeSpiderMultusConfigs struct {
	*gentype.FakeClientWithList[*v2beta1.SpiderMultusConfig, *v2beta1.SpiderMultusConfigList]
	Fake *FakeSpiderpoolV2beta1
}

func newFakeSpiderMultusConfigs(fake *FakeSpiderpoolV2beta1, namespace string) spiderpoolspidernetiov2beta1.SpiderMultusConfigInterface {
	return &fakeSpiderMultusConfigs{
		gentype.NewFakeClientWithList[*v2beta1.SpiderMultusConfig, *v2beta1.SpiderMultusConfigList](
			fake.Fake,
			namespace,
			v2beta1.SchemeGroupVersion.WithResource("spidermultusconfigs"),
			v2beta1.SchemeGroupVersion.WithKind("SpiderMultusConfig"),
			func() *v2beta1.SpiderMultusConfig { return &v2beta1.SpiderMultusConfig{} },
			func() *v2beta1.SpiderMultusConfigList { return &v2beta1.SpiderMultusConfigList{} },
			func(dst, src *v2beta1.SpiderMultusConfigList) { dst.ListMeta = src.ListMeta },
			func(list *v2beta1.SpiderMultusConfigList) []*v2beta1.SpiderMultusConfig {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v2beta1.SpiderMultusConfigList, items []*v2beta1.SpiderMultusConfig) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
