// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v2beta1 "github.com/spidernet-io/spiderpool/pkg/k8s/apis/spiderpool.spidernet.io/v2beta1"
	spiderpoolspidernetiov2beta1 "github.com/spidernet-io/spiderpool/pkg/k8s/client/clientset/versioned/typed/spiderpool.spidernet.io/v2beta1"
	gentype "k8s.io/client-go/gentype"
)

// fakeSpiderIPPools implements SpiderIPPoolInterface
type fakeSpiderIPPools struct {
	*gentype.FakeClientWithList[*v2beta1.SpiderIPPool, *v2beta1.SpiderIPPoolList]
	Fake *FakeSpiderpoolV2beta1
}

func newFakeSpiderIPPools(fake *FakeSpiderpoolV2beta1) spiderpoolspidernetiov2beta1.SpiderIPPoolInterface {
	return &fakeSpiderIPPools{
		gentype.NewFakeClientWithList[*v2beta1.SpiderIPPool, *v2beta1.SpiderIPPoolList](
			fake.Fake,
			"",
			v2beta1.SchemeGroupVersion.WithResource("spiderippools"),
			v2beta1.SchemeGroupVersion.WithKind("SpiderIPPool"),
			func() *v2beta1.SpiderIPPool { return &v2beta1.SpiderIPPool{} },
			func() *v2beta1.SpiderIPPoolList { return &v2beta1.SpiderIPPoolList{} },
			func(dst, src *v2beta1.SpiderIPPoolList) { dst.ListMeta = src.ListMeta },
			func(list *v2beta1.SpiderIPPoolList) []*v2beta1.SpiderIPPool {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v2beta1.SpiderIPPoolList, items []*v2beta1.SpiderIPPool) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
