apiVersion: spiderpool.spidernet.io/v2beta1
kind: SpiderIPPool
metadata:
  name: occupied-static-ipv4-ippool
spec:
  subnet: 172.18.41.0/24
  ips:
    - 172.18.41.40-172.18.41.43
  podAffinity:
    matchLabels:
      app: static
