apiVersion: spiderpool.spidernet.io/v2beta1
kind: SpiderIPPool
metadata:
  name: default-ipv4-ippool
  labels:
    case: backup
spec:
  subnet: 172.18.41.0/24
  ips:
    - 172.18.41.40-172.18.41.41
---
apiVersion: spiderpool.spidernet.io/v2beta1
kind: SpiderIPPool
metadata:
  name: backup-ipv4-ippool
  labels:
    case: backup
spec:
  subnet: 172.18.42.0/24
  ips:
    - 172.18.42.40-172.18.42.41
