// Code generated by go-swagger; DO NOT EDIT.
// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Package server Spiderpool-Agent API
//
//  Spiderpool Agent
//  Schemes:
//    unix
//  Host: localhost
//  BasePath: /v1beta
//  Version: v1beta
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package server
