apiVersion: spiderpool.spidernet.io/v2beta1
kind: SpiderIPPool
metadata:
  name: master-ipv4-ippool
spec:
  subnet: 172.18.41.0/24
  ips:
    - 172.18.41.40
  gateway: 172.18.41.1
  nodeAffinity:
    matchExpressions:
      - {key: node-role.kubernetes.io/master, operator: Exists}
