// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PutIpamIPReader is a Reader for the PutIpamIP structure.
type PutIpamIPReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutIpamIPReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutIpamIPOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewPutIpamIPInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPutIpamIPOK creates a PutIpamIPOK with default headers values
func NewPutIpamIPOK() *PutIpamIPOK {
	return &PutIpamIPOK{}
}

/*
PutIpamIPOK describes a response with status code 200, with default header values.

Success
*/
type PutIpamIPOK struct {
}

// IsSuccess returns true when this put ipam Ip o k response has a 2xx status code
func (o *PutIpamIPOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this put ipam Ip o k response has a 3xx status code
func (o *PutIpamIPOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put ipam Ip o k response has a 4xx status code
func (o *PutIpamIPOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this put ipam Ip o k response has a 5xx status code
func (o *PutIpamIPOK) IsServerError() bool {
	return false
}

// IsCode returns true when this put ipam Ip o k response a status code equal to that given
func (o *PutIpamIPOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the put ipam Ip o k response
func (o *PutIpamIPOK) Code() int {
	return 200
}

func (o *PutIpamIPOK) Error() string {
	return fmt.Sprintf("[PUT /ipam/ip][%d] putIpamIpOK ", 200)
}

func (o *PutIpamIPOK) String() string {
	return fmt.Sprintf("[PUT /ipam/ip][%d] putIpamIpOK ", 200)
}

func (o *PutIpamIPOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPutIpamIPInternalServerError creates a PutIpamIPInternalServerError with default headers values
func NewPutIpamIPInternalServerError() *PutIpamIPInternalServerError {
	return &PutIpamIPInternalServerError{}
}

/*
PutIpamIPInternalServerError describes a response with status code 500, with default header values.

Force set ip failure
*/
type PutIpamIPInternalServerError struct {
}

// IsSuccess returns true when this put ipam Ip internal server error response has a 2xx status code
func (o *PutIpamIPInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this put ipam Ip internal server error response has a 3xx status code
func (o *PutIpamIPInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this put ipam Ip internal server error response has a 4xx status code
func (o *PutIpamIPInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this put ipam Ip internal server error response has a 5xx status code
func (o *PutIpamIPInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this put ipam Ip internal server error response a status code equal to that given
func (o *PutIpamIPInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the put ipam Ip internal server error response
func (o *PutIpamIPInternalServerError) Code() int {
	return 500
}

func (o *PutIpamIPInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /ipam/ip][%d] putIpamIpInternalServerError ", 500)
}

func (o *PutIpamIPInternalServerError) String() string {
	return fmt.Sprintf("[PUT /ipam/ip][%d] putIpamIpInternalServerError ", 500)
}

func (o *PutIpamIPInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
