// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package runtime

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetRuntimeReadinessReader is a Reader for the GetRuntimeReadiness structure.
type GetRuntimeReadinessReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRuntimeReadinessReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetRuntimeReadinessOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetRuntimeReadinessInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetRuntimeReadinessOK creates a GetRuntimeReadinessOK with default headers values
func NewGetRuntimeReadinessOK() *GetRuntimeReadinessOK {
	return &GetRuntimeReadinessOK{}
}

/*
GetRuntimeReadinessOK describes a response with status code 200, with default header values.

Success
*/
type GetRuntimeReadinessOK struct {
}

func (o *GetRuntimeReadinessOK) Error() string {
	return fmt.Sprintf("[GET /runtime/readiness][%d] getRuntimeReadinessOK ", 200)
}

func (o *GetRuntimeReadinessOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetRuntimeReadinessInternalServerError creates a GetRuntimeReadinessInternalServerError with default headers values
func NewGetRuntimeReadinessInternalServerError() *GetRuntimeReadinessInternalServerError {
	return &GetRuntimeReadinessInternalServerError{}
}

/*
GetRuntimeReadinessInternalServerError describes a response with status code 500, with default header values.

Failed
*/
type GetRuntimeReadinessInternalServerError struct {
}

func (o *GetRuntimeReadinessInternalServerError) Error() string {
	return fmt.Sprintf("[GET /runtime/readiness][%d] getRuntimeReadinessInternalServerError ", 500)
}

func (o *GetRuntimeReadinessInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
