apiVersion: spiderpool.spidernet.io/v1
kind: SpiderIPPool
metadata:
  name: static-ipv4-ippool
spec:
  ipVersion: 4
  subnet: 172.18.41.0/24
  ips:
    - 172.18.41.40-172.18.41.43
  podAffinity:
    matchLabels:
      app: static
