name: CI failure
description: Report continuously failing tests or jobs in CI
labels: ["kind/ci-bug"]
assignees: ["cyclinder"]
body:
  - type: textarea
    id: jobs
    attributes:
      label: Which tests are failing?
    validations:
      required: true
  - type: input
    id: testgrid
    attributes:
      label: Job's Link
  - type: textarea
    id: reason
    attributes:
      label: Reason for failure (if possible)
  - type: textarea
    id: additional
    attributes:
      label: Anything else we need to know?
