// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package connectivity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetIpamHealthyHandlerFunc turns a function with the right signature into a get ipam healthy handler
type GetIpamHealthyHandlerFunc func(GetIpamHealthyParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetIpamHealthyHandlerFunc) Handle(params GetIpamHealthyParams) middleware.Responder {
	return fn(params)
}

// GetIpamHealthyHandler interface for that can handle valid get ipam healthy params
type GetIpamHealthyHandler interface {
	Handle(GetIpamHealthyParams) middleware.Responder
}

// NewGetIpamHealthy creates a new http.Handler for the get ipam healthy operation
func NewGetIpamHealthy(ctx *middleware.Context, handler GetIpamHealthyHandler) *GetIpamHealthy {
	return &GetIpamHealthy{Context: ctx, Handler: handler}
}

/*
	GetIpamHealthy swagger:route GET /ipam/healthy connectivity getIpamHealthy

# Get health of spiderpool daemon

Check spiderpool daemonset health to make sure whether it's ready
for CNI plugin usage
*/
type GetIpamHealthy struct {
	Context *middleware.Context
	Handler GetIpamHealthyHandler
}

func (o *GetIpamHealthy) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetIpamHealthyParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
