// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	spiderpoolspidernetiov1 "github.com/spidernet-io/spiderpool/pkg/k8s/apis/spiderpool.spidernet.io/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSpiderReservedIPs implements SpiderReservedIPInterface
type FakeSpiderReservedIPs struct {
	Fake *FakeSpiderpoolV1
	ns   string
}

var spiderreservedipsResource = schema.GroupVersionResource{Group: "spiderpool.spidernet.io", Version: "v1", Resource: "spiderreservedips"}

var spiderreservedipsKind = schema.GroupVersionKind{Group: "spiderpool.spidernet.io", Version: "v1", Kind: "SpiderReservedIP"}

// Get takes name of the spiderReservedIP, and returns the corresponding spiderReservedIP object, and an error if there is any.
func (c *FakeSpiderReservedIPs) Get(ctx context.Context, name string, options v1.GetOptions) (result *spiderpoolspidernetiov1.SpiderReservedIP, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(spiderreservedipsResource, c.ns, name), &spiderpoolspidernetiov1.SpiderReservedIP{})

	if obj == nil {
		return nil, err
	}
	return obj.(*spiderpoolspidernetiov1.SpiderReservedIP), err
}

// List takes label and field selectors, and returns the list of SpiderReservedIPs that match those selectors.
func (c *FakeSpiderReservedIPs) List(ctx context.Context, opts v1.ListOptions) (result *spiderpoolspidernetiov1.SpiderReservedIPList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(spiderreservedipsResource, spiderreservedipsKind, c.ns, opts), &spiderpoolspidernetiov1.SpiderReservedIPList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &spiderpoolspidernetiov1.SpiderReservedIPList{ListMeta: obj.(*spiderpoolspidernetiov1.SpiderReservedIPList).ListMeta}
	for _, item := range obj.(*spiderpoolspidernetiov1.SpiderReservedIPList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested spiderReservedIPs.
func (c *FakeSpiderReservedIPs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(spiderreservedipsResource, c.ns, opts))

}

// Create takes the representation of a spiderReservedIP and creates it.  Returns the server's representation of the spiderReservedIP, and an error, if there is any.
func (c *FakeSpiderReservedIPs) Create(ctx context.Context, spiderReservedIP *spiderpoolspidernetiov1.SpiderReservedIP, opts v1.CreateOptions) (result *spiderpoolspidernetiov1.SpiderReservedIP, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(spiderreservedipsResource, c.ns, spiderReservedIP), &spiderpoolspidernetiov1.SpiderReservedIP{})

	if obj == nil {
		return nil, err
	}
	return obj.(*spiderpoolspidernetiov1.SpiderReservedIP), err
}

// Update takes the representation of a spiderReservedIP and updates it. Returns the server's representation of the spiderReservedIP, and an error, if there is any.
func (c *FakeSpiderReservedIPs) Update(ctx context.Context, spiderReservedIP *spiderpoolspidernetiov1.SpiderReservedIP, opts v1.UpdateOptions) (result *spiderpoolspidernetiov1.SpiderReservedIP, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(spiderreservedipsResource, c.ns, spiderReservedIP), &spiderpoolspidernetiov1.SpiderReservedIP{})

	if obj == nil {
		return nil, err
	}
	return obj.(*spiderpoolspidernetiov1.SpiderReservedIP), err
}

// Delete takes name of the spiderReservedIP and deletes it. Returns an error if one occurs.
func (c *FakeSpiderReservedIPs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(spiderreservedipsResource, c.ns, name, opts), &spiderpoolspidernetiov1.SpiderReservedIP{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSpiderReservedIPs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(spiderreservedipsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &spiderpoolspidernetiov1.SpiderReservedIPList{})
	return err
}

// Patch applies the patch and returns the patched spiderReservedIP.
func (c *FakeSpiderReservedIPs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *spiderpoolspidernetiov1.SpiderReservedIP, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(spiderreservedipsResource, c.ns, name, pt, data, subresources...), &spiderpoolspidernetiov1.SpiderReservedIP{})

	if obj == nil {
		return nil, err
	}
	return obj.(*spiderpoolspidernetiov1.SpiderReservedIP), err
}
