// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/spidernet-io/spiderpool/pkg/k8s/apis/spiderpool.spidernet.io/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSpiderMultusConfigs implements SpiderMultusConfigInterface
type FakeSpiderMultusConfigs struct {
	Fake *FakeSpiderpoolV1
	ns   string
}

var spidermultusconfigsResource = v1.SchemeGroupVersion.WithResource("spidermultusconfigs")

var spidermultusconfigsKind = v1.SchemeGroupVersion.WithKind("SpiderMultusConfig")

// Get takes name of the spiderMultusConfig, and returns the corresponding spiderMultusConfig object, and an error if there is any.
func (c *FakeSpiderMultusConfigs) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.SpiderMultusConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(spidermultusconfigsResource, c.ns, name), &v1.SpiderMultusConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.SpiderMultusConfig), err
}

// List takes label and field selectors, and returns the list of SpiderMultusConfigs that match those selectors.
func (c *FakeSpiderMultusConfigs) List(ctx context.Context, opts metav1.ListOptions) (result *v1.SpiderMultusConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(spidermultusconfigsResource, spidermultusconfigsKind, c.ns, opts), &v1.SpiderMultusConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.SpiderMultusConfigList{ListMeta: obj.(*v1.SpiderMultusConfigList).ListMeta}
	for _, item := range obj.(*v1.SpiderMultusConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested spiderMultusConfigs.
func (c *FakeSpiderMultusConfigs) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(spidermultusconfigsResource, c.ns, opts))

}

// Create takes the representation of a spiderMultusConfig and creates it.  Returns the server's representation of the spiderMultusConfig, and an error, if there is any.
func (c *FakeSpiderMultusConfigs) Create(ctx context.Context, spiderMultusConfig *v1.SpiderMultusConfig, opts metav1.CreateOptions) (result *v1.SpiderMultusConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(spidermultusconfigsResource, c.ns, spiderMultusConfig), &v1.SpiderMultusConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.SpiderMultusConfig), err
}

// Update takes the representation of a spiderMultusConfig and updates it. Returns the server's representation of the spiderMultusConfig, and an error, if there is any.
func (c *FakeSpiderMultusConfigs) Update(ctx context.Context, spiderMultusConfig *v1.SpiderMultusConfig, opts metav1.UpdateOptions) (result *v1.SpiderMultusConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(spidermultusconfigsResource, c.ns, spiderMultusConfig), &v1.SpiderMultusConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.SpiderMultusConfig), err
}

// Delete takes name of the spiderMultusConfig and deletes it. Returns an error if one occurs.
func (c *FakeSpiderMultusConfigs) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(spidermultusconfigsResource, c.ns, name, opts), &v1.SpiderMultusConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSpiderMultusConfigs) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(spidermultusconfigsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.SpiderMultusConfigList{})
	return err
}

// Patch applies the patch and returns the patched spiderMultusConfig.
func (c *FakeSpiderMultusConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.SpiderMultusConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(spidermultusconfigsResource, c.ns, name, pt, data, subresources...), &v1.SpiderMultusConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.SpiderMultusConfig), err
}
