// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/spidernet-io/spiderpool/pkg/k8s/client/clientset/versioned/typed/spiderpool.spidernet.io/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeSpiderpoolV1 struct {
	*testing.Fake
}

func (c *FakeSpiderpoolV1) SpiderEndpoints(namespace string) v1.SpiderEndpointInterface {
	return &FakeSpiderEndpoints{c, namespace}
}

func (c *FakeSpiderpoolV1) SpiderIPPools() v1.SpiderIPPoolInterface {
	return &FakeSpiderIPPools{c}
}

func (c *FakeSpiderpoolV1) SpiderReservedIPs(namespace string) v1.SpiderReservedIPInterface {
	return &FakeSpiderReservedIPs{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeSpiderpoolV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
