apiVersion: spiderpool.spidernet.io/v2beta1
kind: SpiderIPPool
metadata:
  name: worker-ipv4-ippool
spec:
  subnet: 172.18.42.0/24
  ips:
    - 172.18.42.40
  gateway: 172.18.42.1
  nodeAffinity:
    matchExpressions:
      - {key: node-role.kubernetes.io/master, operator: DoesNotExist}
