// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package connectivity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetIpamHealthyParams creates a new GetIpamHealthyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetIpamHealthyParams() *GetIpamHealthyParams {
	return &GetIpamHealthyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetIpamHealthyParamsWithTimeout creates a new GetIpamHealthyParams object
// with the ability to set a timeout on a request.
func NewGetIpamHealthyParamsWithTimeout(timeout time.Duration) *GetIpamHealthyParams {
	return &GetIpamHealthyParams{
		timeout: timeout,
	}
}

// NewGetIpamHealthyParamsWithContext creates a new GetIpamHealthyParams object
// with the ability to set a context for a request.
func NewGetIpamHealthyParamsWithContext(ctx context.Context) *GetIpamHealthyParams {
	return &GetIpamHealthyParams{
		Context: ctx,
	}
}

// NewGetIpamHealthyParamsWithHTTPClient creates a new GetIpamHealthyParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetIpamHealthyParamsWithHTTPClient(client *http.Client) *GetIpamHealthyParams {
	return &GetIpamHealthyParams{
		HTTPClient: client,
	}
}

/*
GetIpamHealthyParams contains all the parameters to send to the API endpoint

	for the get ipam healthy operation.

	Typically these are written to a http.Request.
*/
type GetIpamHealthyParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get ipam healthy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetIpamHealthyParams) WithDefaults() *GetIpamHealthyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get ipam healthy params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetIpamHealthyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get ipam healthy params
func (o *GetIpamHealthyParams) WithTimeout(timeout time.Duration) *GetIpamHealthyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get ipam healthy params
func (o *GetIpamHealthyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get ipam healthy params
func (o *GetIpamHealthyParams) WithContext(ctx context.Context) *GetIpamHealthyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get ipam healthy params
func (o *GetIpamHealthyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get ipam healthy params
func (o *GetIpamHealthyParams) WithHTTPClient(client *http.Client) *GetIpamHealthyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get ipam healthy params
func (o *GetIpamHealthyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetIpamHealthyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
