// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package connectivity

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetIpamHealthyReader is a Reader for the GetIpamHealthy structure.
type GetIpamHealthyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetIpamHealthyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetIpamHealthyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetIpamHealthyInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetIpamHealthyOK creates a GetIpamHealthyOK with default headers values
func NewGetIpamHealthyOK() *GetIpamHealthyOK {
	return &GetIpamHealthyOK{}
}

/*
GetIpamHealthyOK describes a response with status code 200, with default header values.

Success
*/
type GetIpamHealthyOK struct {
}

func (o *GetIpamHealthyOK) Error() string {
	return fmt.Sprintf("[GET /ipam/healthy][%d] getIpamHealthyOK ", 200)
}

func (o *GetIpamHealthyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetIpamHealthyInternalServerError creates a GetIpamHealthyInternalServerError with default headers values
func NewGetIpamHealthyInternalServerError() *GetIpamHealthyInternalServerError {
	return &GetIpamHealthyInternalServerError{}
}

/*
GetIpamHealthyInternalServerError describes a response with status code 500, with default header values.

Failed
*/
type GetIpamHealthyInternalServerError struct {
}

func (o *GetIpamHealthyInternalServerError) Error() string {
	return fmt.Sprintf("[GET /ipam/healthy][%d] getIpamHealthyInternalServerError ", 500)
}

func (o *GetIpamHealthyInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
