// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/spidernet-io/spiderpool/pkg/k8s/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// SpiderEndpoints returns a SpiderEndpointInformer.
	SpiderEndpoints() SpiderEndpointInformer
	// SpiderIPPools returns a SpiderIPPoolInformer.
	SpiderIPPools() SpiderIPPoolInformer
	// SpiderReservedIPs returns a SpiderReservedIPInformer.
	SpiderReservedIPs() SpiderReservedIPInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// SpiderEndpoints returns a SpiderEndpointInformer.
func (v *version) SpiderEndpoints() SpiderEndpointInformer {
	return &spiderEndpointInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// SpiderIPPools returns a SpiderIPPoolInformer.
func (v *version) SpiderIPPools() SpiderIPPoolInformer {
	return &spiderIPPoolInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// SpiderReservedIPs returns a SpiderReservedIPInformer.
func (v *version) SpiderReservedIPs() SpiderReservedIPInformer {
	return &spiderReservedIPInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
