{{- if .Values.multus.multusCNI.install -}}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.multus.multusCNI.name | trunc 63 | trimSuffix "-" }}
rules:
  - apiGroups: ["k8s.cni.cncf.io"]
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/status
    verbs:
      - get
      - update
  - apiGroups:
      - ""
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
      - patch
      - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.multus.multusCNI.name | trunc 63 | trimSuffix "-" }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.multus.multusCNI.name | trunc 63 | trimSuffix "-" }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.multus.multusCNI.name | trunc 63 | trimSuffix "-" }}
    namespace: {{ .Release.Namespace | quote }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.multus.multusCNI.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace | quote }}
{{- if .Values.multus.multusCNI.defaultCniCRName }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: multus-cni-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "spiderpool.multus.labels" . | nindent 4 }}
      {{- if .Values.global.commonLabels }}
      {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
      {{- end }}
data:
  cni-conf.json: |
    {
      "cniVersion": "0.3.1",
      "name": "multus-cni-network",
      "type": "multus",
      "confDir": "/etc/cni/net.d/" ,
      "logLevel": "{{ .Values.multus.multusCNI.log.logLevel }}",
      "logFile": "{{ .Values.multus.multusCNI.log.logFile }}",
      "capabilities": {
        "portMappings": true,
        "bandwidth": true
      },
      "namespaceIsolation": false,
      "clusterNetwork": "{{ .Values.multus.multusCNI.defaultCniCRName }}",
      "defaultNetworks": [],
      "multusNamespace": "{{ .Release.Namespace }}",
      "systemNamespaces": [],
      "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig"
    }
{{- end }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.multus.multusCNI.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "spiderpool.multus.labels" . | nindent 4 }}
      {{- if .Values.global.commonLabels }}
      {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 4 }}
      {{- end }}
  {{- if .Values.global.commonAnnotations }}
  annotations:
    {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "spiderpool.multus.selectorLabels" . | nindent 6 }}
  {{- with .Values.multus.multusCNI.updateStrategy }}
  updateStrategy:
    {{- toYaml . | trim | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
        {{- if .Values.global.commonAnnotations }}
          {{- include "tplvalues.render" ( dict "value" .Values.global.commonAnnotations "context" $ ) | nindent 8 }}
          {{- end }}
          {{- if .Values.multus.multusCNI.podAnnotations }}
          {{- include "tplvalues.render" ( dict "value" .Values.multus.multusCNI.podAnnotations "context" $ ) | nindent 8 }}
          {{- end }}
      labels:
        {{- include "spiderpool.multus.selectorLabels" . | nindent 8 }}
          {{- if .Values.global.commonLabels }}
          {{- include "tplvalues.render" ( dict "value" .Values.global.commonLabels "context" $ ) | nindent 8 }}
          {{- end }}
          {{- if .Values.multus.multusCNI.podLabels }}
          {{- include "tplvalues.render" ( dict "value" .Values.multus.multusCNI.podLabels "context" $ ) | nindent 8 }}
          {{- end }}
    spec:
      hostNetwork: true
      {{- with .Values.multus.multusCNI.tolerations }}
      tolerations:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      serviceAccountName: {{ .Values.multus.multusCNI.name | trunc 63 | trimSuffix "-" }}
      containers:
        - name: kube-multus
          imagePullPolicy: {{ .Values.multus.multusCNI.image.pullPolicy}}
          image: {{ include "spiderpool.multus.image" . | quote }}
          command: ["/entrypoint.sh"]
          args:
            {{- if .Values.multus.multusCNI.defaultCniCRName }}
            - "--multus-conf-file=/tmp/multus-conf/00-multus.conf"
            {{- else }}
            - "--multus-conf-file=auto"
            {{- end }}
            - "--cni-version=0.3.1"
            {{- with .Values.multus.multusCNI.extraArgs }}
            {{- toYaml . | trim | nindent 12 }}
            {{- end }}
          {{- if .Values.multus.multusCNI.extraEnv }}
          env:
            {{- with .Values.multus.multusCNI.extraEnv }}
              {{- toYaml . | nindent 12 }}
              {{- end }}
          {{- end }}
          {{- with .Values.multus.multusCNI.resources }}
          resources:
          {{- toYaml . | trim | nindent 12 }}
          {{- end }}
          {{- with .Values.multus.multusCNI.securityContext }}
          securityContext:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: cni
              mountPath: /host/etc/cni/net.d
            - name: cnibin
              mountPath: /host/opt/cni/bin
            {{- if .Values.multus.multusCNI.defaultCniCRName }}
            - name: multus-cfg
              mountPath: /tmp/multus-conf
            {{- end }}
            {{- if .Values.multus.multusCNI.extraVolumes }}
            {{- include "tplvalues.render" ( dict "value" .Values.multus.multusCNI.extraVolumeMounts "context" $ ) | nindent 12 }}
            {{- end }}
          {{- if .Values.multus.multusCNI.uninstall }}
          lifecycle:
            preStop:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - |
                    rm -f /host/opt/cni/bin/multus || true
                    rm -rf /host/etc/cni/net.d/multus.d || true
                    rm -f /host/etc/cni/net.d/00-multus.conf || true
          {{- end }}
      initContainers:
        - name: install-multus-binary
          imagePullPolicy: {{ .Values.multus.multusCNI.image.pullPolicy}}
          image: {{ include "spiderpool.multus.image" . | quote }}
          command:
            - "/bin/sh"
            - "-c"
            - |
              cp  /usr/src/multus-cni/bin/multus /host/opt/cni/bin/multus
              # TODO: We can revert the changes if https://github.com/k8snetworkplumbingwg/multus-cni/pull/1119 merged.
              {{- if eq .Values.multus.multusCNI.defaultCniCRName "" }}
              cp /host/etc/cni/net.d/*.conf* /host/etc/cni/multus/net.d/
              {{- end }}
          resources:
            requests:
              cpu: "10m"
              memory: "15Mi"
          securityContext:
            privileged: true
          volumeMounts:
            - name: cnibin
              mountPath: /host/opt/cni/bin
              mountPropagation: Bidirectional
            {{- if eq .Values.multus.multusCNI.defaultCniCRName "" }}
            - mountPath: /host/etc/cni/net.d
              name: cni
            - mountPath: /host/etc/cni/multus/net.d
              name: multus-cni-dir
            {{- end }}
      terminationGracePeriodSeconds: 10
      volumes:
        - name: cni
          hostPath:
            path: /etc/cni/net.d
        - name: cnibin
          hostPath:
            path: /opt/cni/bin
        {{- if .Values.multus.multusCNI.defaultCniCRName }}
        - name: multus-cfg
          configMap:
            name: multus-cni-config
            items:
              - key: cni-conf.json
                path: 00-multus.conf
        {{- else }}
        - hostPath:
            path: /etc/cni/multus/net.d
            type: DirectoryOrCreate
          name: multus-cni-dir
        {{- end }}
        {{- if .Values.multus.multusCNI.extraVolumeMounts }}
        {{- include "tplvalues.render" ( dict "value" .Values.multus.multusCNI.extraVolumeMounts "context" $ ) | nindent 8 }}
        {{- end }}
  {{- end }}