// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v2beta1

// SpiderCoordinatorListerExpansion allows custom methods to be added to
// SpiderCoordinatorLister.
type SpiderCoordinatorListerExpansion interface{}

// SpiderIPPoolListerExpansion allows custom methods to be added to
// SpiderIPPoolLister.
type SpiderIPPoolListerExpansion interface{}

// SpiderMultusConfigListerExpansion allows custom methods to be added to
// SpiderMultusConfigLister.
type SpiderMultusConfigListerExpansion interface{}

// SpiderMultusConfigNamespaceListerExpansion allows custom methods to be added to
// SpiderMultusConfigNamespaceLister.
type SpiderMultusConfigNamespaceListerExpansion interface{}

// SpiderSubnetListerExpansion allows custom methods to be added to
// SpiderSubnetLister.
type SpiderSubnetListerExpansion interface{}
