// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v2beta1

import (
	spiderpoolspidernetiov2beta1 "github.com/spidernet-io/spiderpool/pkg/k8s/apis/spiderpool.spidernet.io/v2beta1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// SpiderCNIConfigLister helps list SpiderCNIConfigs.
// All objects returned here must be treated as read-only.
type SpiderCNIConfigLister interface {
	// List lists all SpiderCNIConfigs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*spiderpoolspidernetiov2beta1.SpiderCNIConfig, err error)
	// SpiderCNIConfigs returns an object that can list and get SpiderCNIConfigs.
	SpiderCNIConfigs(namespace string) SpiderCNIConfigNamespaceLister
	SpiderCNIConfigListerExpansion
}

// spiderCNIConfigLister implements the SpiderCNIConfigLister interface.
type spiderCNIConfigLister struct {
	listers.ResourceIndexer[*spiderpoolspidernetiov2beta1.SpiderCNIConfig]
}

// NewSpiderCNIConfigLister returns a new SpiderCNIConfigLister.
func NewSpiderCNIConfigLister(indexer cache.Indexer) SpiderCNIConfigLister {
	return &spiderCNIConfigLister{listers.New[*spiderpoolspidernetiov2beta1.SpiderCNIConfig](indexer, spiderpoolspidernetiov2beta1.Resource("spidercniconfig"))}
}

// SpiderCNIConfigs returns an object that can list and get SpiderCNIConfigs.
func (s *spiderCNIConfigLister) SpiderCNIConfigs(namespace string) SpiderCNIConfigNamespaceLister {
	return spiderCNIConfigNamespaceLister{listers.NewNamespaced[*spiderpoolspidernetiov2beta1.SpiderCNIConfig](s.ResourceIndexer, namespace)}
}

// SpiderCNIConfigNamespaceLister helps list and get SpiderCNIConfigs.
// All objects returned here must be treated as read-only.
type SpiderCNIConfigNamespaceLister interface {
	// List lists all SpiderCNIConfigs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*spiderpoolspidernetiov2beta1.SpiderCNIConfig, err error)
	// Get retrieves the SpiderCNIConfig from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*spiderpoolspidernetiov2beta1.SpiderCNIConfig, error)
	SpiderCNIConfigNamespaceListerExpansion
}

// spiderCNIConfigNamespaceLister implements the SpiderCNIConfigNamespaceLister
// interface.
type spiderCNIConfigNamespaceLister struct {
	listers.ResourceIndexer[*spiderpoolspidernetiov2beta1.SpiderCNIConfig]
}
