// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package daemonset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/spidernet-io/spiderpool/api/v1/agent/models"
)

// DeleteIpamIpsOKCode is the HTTP code returned for type DeleteIpamIpsOK
const DeleteIpamIpsOKCode int = 200

/*
DeleteIpamIpsOK Success

swagger:response deleteIpamIpsOK
*/
type DeleteIpamIpsOK struct {
}

// NewDeleteIpamIpsOK creates DeleteIpamIpsOK with default headers values
func NewDeleteIpamIpsOK() *DeleteIpamIpsOK {

	return &DeleteIpamIpsOK{}
}

// WriteResponse to the client
func (o *DeleteIpamIpsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteIpamIpsFailureCode is the HTTP code returned for type DeleteIpamIpsFailure
const DeleteIpamIpsFailureCode int = 500

/*
DeleteIpamIpsFailure Addresses release failure

swagger:response deleteIpamIpsFailure
*/
type DeleteIpamIpsFailure struct {

	/*
	  In: Body
	*/
	Payload models.Error `json:"body,omitempty"`
}

// NewDeleteIpamIpsFailure creates DeleteIpamIpsFailure with default headers values
func NewDeleteIpamIpsFailure() *DeleteIpamIpsFailure {

	return &DeleteIpamIpsFailure{}
}

// WithPayload adds the payload to the delete ipam ips failure response
func (o *DeleteIpamIpsFailure) WithPayload(payload models.Error) *DeleteIpamIpsFailure {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete ipam ips failure response
func (o *DeleteIpamIpsFailure) SetPayload(payload models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteIpamIpsFailure) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DeleteIpamIpsStatus521Code is the HTTP code returned for type DeleteIpamIpsStatus521
const DeleteIpamIpsStatus521Code int = 521

/*
DeleteIpamIpsStatus521 Forbid to release IPs for stateless workload

swagger:response deleteIpamIpsStatus521
*/
type DeleteIpamIpsStatus521 struct {

	/*
	  In: Body
	*/
	Payload models.Error `json:"body,omitempty"`
}

// NewDeleteIpamIpsStatus521 creates DeleteIpamIpsStatus521 with default headers values
func NewDeleteIpamIpsStatus521() *DeleteIpamIpsStatus521 {

	return &DeleteIpamIpsStatus521{}
}

// WithPayload adds the payload to the delete ipam ips status521 response
func (o *DeleteIpamIpsStatus521) WithPayload(payload models.Error) *DeleteIpamIpsStatus521 {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete ipam ips status521 response
func (o *DeleteIpamIpsStatus521) SetPayload(payload models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteIpamIpsStatus521) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(521)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// DeleteIpamIpsStatus522Code is the HTTP code returned for type DeleteIpamIpsStatus522
const DeleteIpamIpsStatus522Code int = 522

/*
DeleteIpamIpsStatus522 Forbid to release IPs for stateful workload

swagger:response deleteIpamIpsStatus522
*/
type DeleteIpamIpsStatus522 struct {

	/*
	  In: Body
	*/
	Payload models.Error `json:"body,omitempty"`
}

// NewDeleteIpamIpsStatus522 creates DeleteIpamIpsStatus522 with default headers values
func NewDeleteIpamIpsStatus522() *DeleteIpamIpsStatus522 {

	return &DeleteIpamIpsStatus522{}
}

// WithPayload adds the payload to the delete ipam ips status522 response
func (o *DeleteIpamIpsStatus522) WithPayload(payload models.Error) *DeleteIpamIpsStatus522 {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete ipam ips status522 response
func (o *DeleteIpamIpsStatus522) SetPayload(payload models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteIpamIpsStatus522) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(522)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
