// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package daemonset

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostIpamIpsOKCode is the HTTP code returned for type PostIpamIpsOK
const PostIpamIpsOKCode int = 200

/*
PostIpamIpsOK Success

swagger:response postIpamIpsOK
*/
type PostIpamIpsOK struct {
}

// NewPostIpamIpsOK creates PostIpamIpsOK with default headers values
func NewPostIpamIpsOK() *PostIpamIpsOK {

	return &PostIpamIpsOK{}
}

// WriteResponse to the client
func (o *PostIpamIpsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostIpamIpsInternalServerErrorCode is the HTTP code returned for type PostIpamIpsInternalServerError
const PostIpamIpsInternalServerErrorCode int = 500

/*
PostIpamIpsInternalServerError Allocation failure

swagger:response postIpamIpsInternalServerError
*/
type PostIpamIpsInternalServerError struct {
}

// NewPostIpamIpsInternalServerError creates PostIpamIpsInternalServerError with default headers values
func NewPostIpamIpsInternalServerError() *PostIpamIpsInternalServerError {

	return &PostIpamIpsInternalServerError{}
}

// WriteResponse to the client
func (o *PostIpamIpsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
