// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by lister-gen. DO NOT EDIT.

package v1

// SpiderEndpointListerExpansion allows custom methods to be added to
// SpiderEndpointLister.
type SpiderEndpointListerExpansion interface{}

// SpiderEndpointNamespaceListerExpansion allows custom methods to be added to
// SpiderEndpointNamespaceLister.
type SpiderEndpointNamespaceListerExpansion interface{}

// SpiderIPPoolListerExpansion allows custom methods to be added to
// SpiderIPPoolLister.
type SpiderIPPoolListerExpansion interface{}

// SpiderReservedIPListerExpansion allows custom methods to be added to
// SpiderReservedIPLister.
type SpiderReservedIPListerExpansion interface{}

// SpiderReservedIPNamespaceListerExpansion allows custom methods to be added to
// SpiderReservedIPNamespaceLister.
type SpiderReservedIPNamespaceListerExpansion interface{}
