// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostIpamGcIpsOKCode is the HTTP code returned for type PostIpamGcIpsOK
const PostIpamGcIpsOKCode int = 200

/*
PostIpamGcIpsOK Success

swagger:response postIpamGcIpsOK
*/
type PostIpamGcIpsOK struct {
}

// NewPostIpamGcIpsOK creates PostIpamGcIpsOK with default headers values
func NewPostIpamGcIpsOK() *PostIpamGcIpsOK {

	return &PostIpamGcIpsOK{}
}

// WriteResponse to the client
func (o *PostIpamGcIpsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PostIpamGcIpsInternalServerErrorCode is the HTTP code returned for type PostIpamGcIpsInternalServerError
const PostIpamGcIpsInternalServerErrorCode int = 500

/*
PostIpamGcIpsInternalServerError Global gc failure

swagger:response postIpamGcIpsInternalServerError
*/
type PostIpamGcIpsInternalServerError struct {
}

// NewPostIpamGcIpsInternalServerError creates PostIpamGcIpsInternalServerError with default headers values
func NewPostIpamGcIpsInternalServerError() *PostIpamGcIpsInternalServerError {

	return &PostIpamGcIpsInternalServerError{}
}

// WriteResponse to the client
func (o *PostIpamGcIpsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
