// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by informer-gen. DO NOT EDIT.

package v2beta2

import (
	"context"
	time "time"

	spiderpoolspidernetiov2beta2 "github.com/spidernet-io/spiderpool/pkg/k8s/apis/spiderpool.spidernet.io/v2beta2"
	versioned "github.com/spidernet-io/spiderpool/pkg/k8s/client/clientset/versioned"
	internalinterfaces "github.com/spidernet-io/spiderpool/pkg/k8s/client/informers/externalversions/internalinterfaces"
	v2beta2 "github.com/spidernet-io/spiderpool/pkg/k8s/client/listers/spiderpool.spidernet.io/v2beta2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SpiderClaimParameterInformer provides access to a shared informer and lister for
// SpiderClaimParameters.
type SpiderClaimParameterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v2beta2.SpiderClaimParameterLister
}

type spiderClaimParameterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSpiderClaimParameterInformer constructs a new informer for SpiderClaimParameter type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSpiderClaimParameterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSpiderClaimParameterInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSpiderClaimParameterInformer constructs a new informer for SpiderClaimParameter type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSpiderClaimParameterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SpiderpoolV2beta2().SpiderClaimParameters(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.SpiderpoolV2beta2().SpiderClaimParameters(namespace).Watch(context.TODO(), options)
			},
		},
		&spiderpoolspidernetiov2beta2.SpiderClaimParameter{},
		resyncPeriod,
		indexers,
	)
}

func (f *spiderClaimParameterInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSpiderClaimParameterInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *spiderClaimParameterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&spiderpoolspidernetiov2beta2.SpiderClaimParameter{}, f.defaultInformer)
}

func (f *spiderClaimParameterInformer) Lister() v2beta2.SpiderClaimParameterLister {
	return v2beta2.NewSpiderClaimParameterLister(f.Informer().GetIndexer())
}
