// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by MockGen. DO NOT EDIT.
// Source: ./reservedip_manager.go

// Package mock_reservedipmanager is a generated GoMock package.
package mock_reservedipmanager

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1 "github.com/spidernet-io/spiderpool/pkg/k8s/apis/spiderpool.spidernet.io/v1"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockReservedIPManager is a mock of ReservedIPManager interface.
type MockReservedIPManager struct {
	ctrl     *gomock.Controller
	recorder *MockReservedIPManagerMockRecorder
}

// MockReservedIPManagerMockRecorder is the mock recorder for MockReservedIPManager.
type MockReservedIPManagerMockRecorder struct {
	mock *MockReservedIPManager
}

// NewMockReservedIPManager creates a new mock instance.
func NewMockReservedIPManager(ctrl *gomock.Controller) *MockReservedIPManager {
	mock := &MockReservedIPManager{ctrl: ctrl}
	mock.recorder = &MockReservedIPManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReservedIPManager) EXPECT() *MockReservedIPManagerMockRecorder {
	return m.recorder
}

// GetReservedIPByName mocks base method.
func (m *MockReservedIPManager) GetReservedIPByName(ctx context.Context, rIPName string) (*v1.SpiderReservedIP, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReservedIPByName", ctx, rIPName)
	ret0, _ := ret[0].(*v1.SpiderReservedIP)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReservedIPByName indicates an expected call of GetReservedIPByName.
func (mr *MockReservedIPManagerMockRecorder) GetReservedIPByName(ctx, rIPName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReservedIPByName", reflect.TypeOf((*MockReservedIPManager)(nil).GetReservedIPByName), ctx, rIPName)
}

// ListReservedIPs mocks base method.
func (m *MockReservedIPManager) ListReservedIPs(ctx context.Context, opts ...client.ListOption) (*v1.SpiderReservedIPList, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListReservedIPs", varargs...)
	ret0, _ := ret[0].(*v1.SpiderReservedIPList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReservedIPs indicates an expected call of ListReservedIPs.
func (mr *MockReservedIPManagerMockRecorder) ListReservedIPs(ctx interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReservedIPs", reflect.TypeOf((*MockReservedIPManager)(nil).ListReservedIPs), varargs...)
}
