// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v2beta1

type SpiderCNIConfigExpansion interface{}

type SpiderCoordinatorExpansion interface{}

type SpiderIPPoolExpansion interface{}

type SpiderMultusConfigExpansion interface{}

type SpiderSubnetExpansion interface{}
