// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v2beta1

import (
	context "context"

	spiderpoolspidernetiov2beta1 "github.com/spidernet-io/spiderpool/pkg/k8s/apis/spiderpool.spidernet.io/v2beta1"
	scheme "github.com/spidernet-io/spiderpool/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// SpiderCoordinatorsGetter has a method to return a SpiderCoordinatorInterface.
// A group's client should implement this interface.
type SpiderCoordinatorsGetter interface {
	SpiderCoordinators() SpiderCoordinatorInterface
}

// SpiderCoordinatorInterface has methods to work with SpiderCoordinator resources.
type SpiderCoordinatorInterface interface {
	Create(ctx context.Context, spiderCoordinator *spiderpoolspidernetiov2beta1.SpiderCoordinator, opts v1.CreateOptions) (*spiderpoolspidernetiov2beta1.SpiderCoordinator, error)
	Update(ctx context.Context, spiderCoordinator *spiderpoolspidernetiov2beta1.SpiderCoordinator, opts v1.UpdateOptions) (*spiderpoolspidernetiov2beta1.SpiderCoordinator, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, spiderCoordinator *spiderpoolspidernetiov2beta1.SpiderCoordinator, opts v1.UpdateOptions) (*spiderpoolspidernetiov2beta1.SpiderCoordinator, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*spiderpoolspidernetiov2beta1.SpiderCoordinator, error)
	List(ctx context.Context, opts v1.ListOptions) (*spiderpoolspidernetiov2beta1.SpiderCoordinatorList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *spiderpoolspidernetiov2beta1.SpiderCoordinator, err error)
	SpiderCoordinatorExpansion
}

// spiderCoordinators implements SpiderCoordinatorInterface
type spiderCoordinators struct {
	*gentype.ClientWithList[*spiderpoolspidernetiov2beta1.SpiderCoordinator, *spiderpoolspidernetiov2beta1.SpiderCoordinatorList]
}

// newSpiderCoordinators returns a SpiderCoordinators
func newSpiderCoordinators(c *SpiderpoolV2beta1Client) *spiderCoordinators {
	return &spiderCoordinators{
		gentype.NewClientWithList[*spiderpoolspidernetiov2beta1.SpiderCoordinator, *spiderpoolspidernetiov2beta1.SpiderCoordinatorList](
			"spidercoordinators",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *spiderpoolspidernetiov2beta1.SpiderCoordinator {
				return &spiderpoolspidernetiov2beta1.SpiderCoordinator{}
			},
			func() *spiderpoolspidernetiov2beta1.SpiderCoordinatorList {
				return &spiderpoolspidernetiov2beta1.SpiderCoordinatorList{}
			},
		),
	}
}
