// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v2beta1

import (
	context "context"

	spiderpoolspidernetiov2beta1 "github.com/spidernet-io/spiderpool/pkg/k8s/apis/spiderpool.spidernet.io/v2beta1"
	scheme "github.com/spidernet-io/spiderpool/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// SpiderSubnetsGetter has a method to return a SpiderSubnetInterface.
// A group's client should implement this interface.
type SpiderSubnetsGetter interface {
	SpiderSubnets() SpiderSubnetInterface
}

// SpiderSubnetInterface has methods to work with SpiderSubnet resources.
type SpiderSubnetInterface interface {
	Create(ctx context.Context, spiderSubnet *spiderpoolspidernetiov2beta1.SpiderSubnet, opts v1.CreateOptions) (*spiderpoolspidernetiov2beta1.SpiderSubnet, error)
	Update(ctx context.Context, spiderSubnet *spiderpoolspidernetiov2beta1.SpiderSubnet, opts v1.UpdateOptions) (*spiderpoolspidernetiov2beta1.SpiderSubnet, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, spiderSubnet *spiderpoolspidernetiov2beta1.SpiderSubnet, opts v1.UpdateOptions) (*spiderpoolspidernetiov2beta1.SpiderSubnet, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*spiderpoolspidernetiov2beta1.SpiderSubnet, error)
	List(ctx context.Context, opts v1.ListOptions) (*spiderpoolspidernetiov2beta1.SpiderSubnetList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *spiderpoolspidernetiov2beta1.SpiderSubnet, err error)
	SpiderSubnetExpansion
}

// spiderSubnets implements SpiderSubnetInterface
type spiderSubnets struct {
	*gentype.ClientWithList[*spiderpoolspidernetiov2beta1.SpiderSubnet, *spiderpoolspidernetiov2beta1.SpiderSubnetList]
}

// newSpiderSubnets returns a SpiderSubnets
func newSpiderSubnets(c *SpiderpoolV2beta1Client) *spiderSubnets {
	return &spiderSubnets{
		gentype.NewClientWithList[*spiderpoolspidernetiov2beta1.SpiderSubnet, *spiderpoolspidernetiov2beta1.SpiderSubnetList](
			"spidersubnets",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *spiderpoolspidernetiov2beta1.SpiderSubnet { return &spiderpoolspidernetiov2beta1.SpiderSubnet{} },
			func() *spiderpoolspidernetiov2beta1.SpiderSubnetList {
				return &spiderpoolspidernetiov2beta1.SpiderSubnetList{}
			},
		),
	}
}
