// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v2beta1

import (
	context "context"

	spiderpoolspidernetiov2beta1 "github.com/spidernet-io/spiderpool/pkg/k8s/apis/spiderpool.spidernet.io/v2beta1"
	scheme "github.com/spidernet-io/spiderpool/pkg/k8s/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// SpiderIPPoolsGetter has a method to return a SpiderIPPoolInterface.
// A group's client should implement this interface.
type SpiderIPPoolsGetter interface {
	SpiderIPPools() SpiderIPPoolInterface
}

// SpiderIPPoolInterface has methods to work with SpiderIPPool resources.
type SpiderIPPoolInterface interface {
	Create(ctx context.Context, spiderIPPool *spiderpoolspidernetiov2beta1.SpiderIPPool, opts v1.CreateOptions) (*spiderpoolspidernetiov2beta1.SpiderIPPool, error)
	Update(ctx context.Context, spiderIPPool *spiderpoolspidernetiov2beta1.SpiderIPPool, opts v1.UpdateOptions) (*spiderpoolspidernetiov2beta1.SpiderIPPool, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, spiderIPPool *spiderpoolspidernetiov2beta1.SpiderIPPool, opts v1.UpdateOptions) (*spiderpoolspidernetiov2beta1.SpiderIPPool, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*spiderpoolspidernetiov2beta1.SpiderIPPool, error)
	List(ctx context.Context, opts v1.ListOptions) (*spiderpoolspidernetiov2beta1.SpiderIPPoolList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *spiderpoolspidernetiov2beta1.SpiderIPPool, err error)
	SpiderIPPoolExpansion
}

// spiderIPPools implements SpiderIPPoolInterface
type spiderIPPools struct {
	*gentype.ClientWithList[*spiderpoolspidernetiov2beta1.SpiderIPPool, *spiderpoolspidernetiov2beta1.SpiderIPPoolList]
}

// newSpiderIPPools returns a SpiderIPPools
func newSpiderIPPools(c *SpiderpoolV2beta1Client) *spiderIPPools {
	return &spiderIPPools{
		gentype.NewClientWithList[*spiderpoolspidernetiov2beta1.SpiderIPPool, *spiderpoolspidernetiov2beta1.SpiderIPPoolList](
			"spiderippools",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *spiderpoolspidernetiov2beta1.SpiderIPPool { return &spiderpoolspidernetiov2beta1.SpiderIPPool{} },
			func() *spiderpoolspidernetiov2beta1.SpiderIPPoolList {
				return &spiderpoolspidernetiov2beta1.SpiderIPPoolList{}
			},
		),
	}
}
