apiVersion: spiderpool.spidernet.io/v2beta1
kind: SpiderSubnet
metadata:
  name: ipv4-subnet-route
spec:
  subnet: 172.18.41.0/24
  ips:
    - 172.18.41.41-172.18.41.60
  routes:
    - dst: 172.18.42.0/24
      gw: 172.18.41.1
