name: Auto PR E2E CI

permissions: write-all

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:
    inputs:
      ref:
        description: 'sha, tag, branch'
        required: true
        default: main
      e2e_labels:
        description: 'e2e labels(if not set, ginkgo will run all test, multi labels separated by commas)'
        required: false
        type: string
      ipfamily:
        description: 'IP family for the e2e test'
        required: true
        type: choice
        default: 'dual'
        options:
          - ipv4
          - ipv6
          - dual
          - all

jobs:
  get_ref:
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ env.RUN_REF }}
      e2e_labels: ${{ env.RUN_E2E_LABELS }}
      unittest_enabled: ${{ env.RUN_UNITTEST_ENABLED }}
      e2e_enabled: ${{ env.RUN_E2E_ENABLED }}
      ipfamily_ipv4only_e2e: ${{ env.RUN_E2E_IPV4_ONLY }}
      ipfamily_ipv6only_e2e: ${{ env.RUN_E2E_IPV6_ONLY }}
      ipfamily_dual_e2e: ${{ env.RUN_E2E_DUAL_STACK }}
    steps:
      - name: Check Code Changes
        uses: dorny/paths-filter@v2.11.1
        if: ${{ github.event_name == 'pull_request_target' }}
        id: filter_pr
        with:
          base: ${{ github.event.pull_request.base.sha }}
          ref: ${{ github.event.pull_request.head.sha }}
          filters: |
            run_e2e:
              - '**/*.sh'
              - '**/*.go'
              - 'go.mod'
              - 'go.sum'
              - 'charts/**'
              - 'Makefile*'
              - '**/Makefile*'
              - '**/Dockerfile'
            all_e2e:
              - 'test/**'
              - 'vendor/github.com/spidernet-io/**/*.go'

      - name: Get Ref
        id: get_ref
        run: |
          if ${{ github.event_name == 'workflow_dispatch' }} ; then
            echo "call by self workflow_dispatch"
            echo "RUN_UNITTEST_ENABLED=true" >> $GITHUB_ENV
            echo "RUN_E2E_ENABLED=true" >> $GITHUB_ENV
            echo "RUN_E2E_LABELS=${{ github.event.inputs.e2e_labels }}" >> $GITHUB_ENV
            echo "RUN_TAG=${{ github.event.inputs.ref }}" >> $GITHUB_ENV
            if ${{ github.event.inputs.ipfamily == 'ipv4' }}; then
              echo "RUN_E2E_IPV4_ONLY=true" >> $GITHUB_ENV
              echo "RUN_E2E_IPV6_ONLY=false" >> $GITHUB_ENV
              echo "RUN_E2E_DUAL_STACK=false" >> $GITHUB_ENV
            elif ${{ github.event.inputs.ipfamily == 'ipv6' }}; then
              echo "RUN_E2E_IPV4_ONLY=false" >> $GITHUB_ENV
              echo "RUN_E2E_IPV6_ONLY=true" >> $GITHUB_ENV
              echo "RUN_E2E_DUAL_STACK=false" >> $GITHUB_ENV
            elif ${{ github.event.inputs.ipfamily == 'dual' }}; then
              echo "RUN_E2E_IPV4_ONLY=false" >> $GITHUB_ENV
              echo "RUN_E2E_IPV6_ONLY=false" >> $GITHUB_ENV
              echo "RUN_E2E_DUAL_STACK=true" >> $GITHUB_ENV
            elif ${{ github.event.inputs.ipfamily == 'all' }}; then
              echo "RUN_E2E_IPV4_ONLY=true" >> $GITHUB_ENV
              echo "RUN_E2E_IPV6_ONLY=true" >> $GITHUB_ENV
              echo "RUN_E2E_DUAL_STACK=true" >> $GITHUB_ENV
            else
              echo "error, unknown input ipfamily: ${{ github.event.inputs.ipfamily }} "
              exit 1
            fi
          elif ${{ github.event_name == 'push' }} ; then
            echo "trigger by push"
            echo "RUN_TAG=${{ github.sha }}" >> $GITHUB_ENV
            echo "RUN_E2E_LABELS=smoke" >> $GITHUB_ENV
            echo "RUN_E2E_ENABLED=true" >> $GITHUB_ENV
            # do it in another workflow
            echo "RUN_UNITTEST_ENABLED=false" >> $GITHUB_ENV
            echo "RUN_E2E_IPV4_ONLY=false" >> $GITHUB_ENV
            echo "RUN_E2E_IPV6_ONLY=false" >> $GITHUB_ENV
            echo "RUN_E2E_DUAL_STACK=true" >> $GITHUB_ENV
          elif ${{ github.event_name == 'pull_request_target' }} ; then
            echo "trigger by pull_request_target"
            echo "RUN_TAG=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
            if ${{ steps.filter_pr.outputs.all_e2e == 'true' }} ; then
                # run all e2e
                echo "RUN_E2E_LABEL=" >> $GITHUB_ENV
                echo "RUN_E2E_IPV4_ONLY=true" >> $GITHUB_ENV
                echo "RUN_E2E_IPV6_ONLY=true" >> $GITHUB_ENV
                echo "RUN_E2E_DUAL_STACK=true" >> $GITHUB_ENV
            else
                echo "RUN_E2E_LABEL=smoke" >> $GITHUB_ENV
                echo "RUN_E2E_IPV4_ONLY=true" >> $GITHUB_ENV
                echo "RUN_E2E_IPV6_ONLY=true" >> $GITHUB_ENV
                echo "RUN_E2E_DUAL_STACK=true" >> $GITHUB_ENV
            fi
              echo "RUN_E2E_ENABLED=${{ steps.filter_pr.outputs.run_e2e }}" >> $GITHUB_ENV
              # do it in another workflow
              echo "RUN_UNITTEST_ENABLED=false" >> $GITHUB_ENV
          else
            # call by auto-nightly-ci, the event is schedule or its workflow_dispatch
            # use main sha for ci image tag
            echo "trigger by workflow_call"
            echo "RUN_TAG=main" >> $GITHUB_ENV
            echo "RUN_E2E_LABEL=" >> $GITHUB_ENV
            echo "RUN_E2E_ENABLED=true" >> $GITHUB_ENV
            echo "RUN_UNITTEST_ENABLED=true" >> $GITHUB_ENV
            if ${{ inputs.ipfamily == 'ipv4' }}; then
              echo "RUN_E2E_IPV4_ONLY=true" >> $GITHUB_ENV
              echo "RUN_E2E_IPV6_ONLY=false" >> $GITHUB_ENV
              echo "RUN_E2E_DUAL_STACK=false" >> $GITHUB_ENV
            elif ${{ inputs.ipfamily == 'ipv6' }}; then
              echo "RUN_E2E_IPV4_ONLY=false" >> $GITHUB_ENV
              echo "RUN_E2E_IPV6_ONLY=true" >> $GITHUB_ENV
              echo "RUN_E2E_DUAL_STACK=false" >> $GITHUB_ENV
            elif ${{ inputs.ipfamily == 'dual' }}; then
              echo "RUN_E2E_IPV4_ONLY=false" >> $GITHUB_ENV
              echo "RUN_E2E_IPV6_ONLY=false" >> $GITHUB_ENV
              echo "RUN_E2E_DUAL_STACK=true" >> $GITHUB_ENV
            elif ${{ inputs.ipfamily == 'all' }}; then
              echo "RUN_E2E_IPV4_ONLY=true" >> $GITHUB_ENV
              echo "RUN_E2E_IPV6_ONLY=true" >> $GITHUB_ENV
              echo "RUN_E2E_DUAL_STACK=true" >> $GITHUB_ENV
            else
              echo "RUN_E2E_IPV4_ONLY=true" >> $GITHUB_ENV
              echo "RUN_E2E_IPV6_ONLY=true" >> $GITHUB_ENV
              echo "RUN_E2E_DUAL_STACK=true" >> $GITHUB_ENV
            fi
          fi

      # some event, the tag is not sha, so checkout it and get sha
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: ${{ env.RUN_TAG }}

      - name: Result Ref
        id: result
        run: |
          ref=$( git show -s --format='format:%H')
          echo "RUN_REF=${ref}" >> $GITHUB_ENV

  call_unittest:
    needs: get_ref
    if: ${{ needs.get_ref.outputs.unittest_enabled == 'true' }}
    # forbid to specify version for local workflow, GITHUB_REF Same as the caller workflow
    uses: ./.github/workflows/lint-golang.yaml
    with:
      ref: ${{ needs.get_ref.outputs.ref }}
    secrets: inherit

  call_build_ci_image:
    needs: [get_ref]
    if: ${{ needs.get_ref.outputs.e2e_enabled == 'true' }}
    # get  image:${{ needs.get_ref.outputs.ref }} and image-ci:${{ needs.get_ref.outputs.ref }}
    uses: ./.github/workflows/build-image-ci.yaml
    with:
      ref: ${{ needs.get_ref.outputs.ref }}
      push: false
    secrets: inherit

  lint_chart_against_release_image:
    needs: get_ref
    if: ${{ needs.get_ref.outputs.e2e_enabled == 'true' }}
    # forbid to specify version for local workflow, GITHUB_REF Same as the caller workflow
    uses: ./.github/workflows/call-lint-chart.yaml
    with:
      ref: ${{ needs.get_ref.outputs.ref }}
    secrets: inherit

  call_release_chart:
    needs: [get_ref]
    if: ${{ needs.get_ref.outputs.e2e_enabled == 'true' }}
    uses: ./.github/workflows/call-release-chart.yaml
    with:
      ref: ${{ needs.get_ref.outputs.ref }}
      submit: false
    secrets: inherit

  trivy_scan_images:
    needs: [call_build_ci_image, get_ref, call_release_chart]
    uses: ./.github/workflows/trivy-scan-image.yaml
    with:
      image_tag: ${{ needs.call_build_ci_image.outputs.imageTag }}
      ref: ${{ needs.get_ref.outputs.ref }}
    secrets: inherit

  call_e2e_dual:
    needs: [call_build_ci_image, get_ref, call_release_chart]
    if: ${{ needs.get_ref.outputs.e2e_enabled == 'true' && needs.get_ref.outputs.ipfamily_dual_e2e == 'true' }}
    uses: ./.github/workflows/e2e-init.yaml
    with:
      ip_family: dual
      image_tag: ${{ needs.call_build_ci_image.outputs.imageTag }}
      ref: ${{ needs.get_ref.outputs.ref }}
      e2e_labels: ${{ needs.get_ref.outputs.e2e_labels }}
    secrets: inherit

  call_e2e_ipv4:
    needs: [call_build_ci_image, get_ref, call_release_chart]
    if: ${{ needs.get_ref.outputs.e2e_enabled == 'true' && needs.get_ref.outputs.ipfamily_ipv4only_e2e == 'true' }}
    uses: ./.github/workflows/e2e-init.yaml
    with:
      ip_family: ipv4
      image_tag: ${{ needs.call_build_ci_image.outputs.imageTag }}
      ref: ${{ needs.get_ref.outputs.ref }}
      e2e_labels: ${{ needs.get_ref.outputs.e2e_labels }}
    secrets: inherit

  call_e2e_ipv6:
    needs: [call_build_ci_image, get_ref, call_release_chart]
    if: ${{ needs.get_ref.outputs.e2e_enabled == 'true' && needs.get_ref.outputs.ipfamily_ipv6only_e2e == 'true' }}
    uses: ./.github/workflows/e2e-init.yaml
    with:
      ip_family: ipv6
      image_tag: ${{ needs.call_build_ci_image.outputs.imageTag }}
      ref: ${{ needs.get_ref.outputs.ref }}
      e2e_labels: ${{ needs.get_ref.outputs.e2e_labels }}
    secrets: inherit

  call_e2e_dual_for_low_kernel:
    needs: [call_build_ci_image, get_ref, call_release_chart]
    if: ${{ needs.get_ref.outputs.e2e_enabled == 'true' && needs.get_ref.outputs.ipfamily_dual_e2e == 'true' }}
    uses: ./.github/workflows/e2e-init.yaml
    with:
      os: ubuntu-20.04
      ip_family: dual
      image_tag: ${{ needs.call_build_ci_image.outputs.imageTag }}
      ref: ${{ needs.get_ref.outputs.ref }}
      e2e_labels: ${{ needs.get_ref.outputs.e2e_labels }}
      k8s_version: v1.27.1
    secrets: inherit
