name: Auto Openapi Lint

on:
  push:
    branches:
      - main
      - release-*
    paths:
      - 'api/**/openapi.yaml'
  pull_request:
    branches:
      - main
      - release-*
    paths:
      - 'api/**/openapi.yaml'
  workflow_dispatch:
    inputs:
      ref:
        description: 'check for branch, sha, tag'
        required: true
        default: main
      path:
        description: 'openapi yaml path'
        required: true

jobs:
  link-check:
    name: Openapi Lint
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - openapifilepath: 'api/v1/agent/openapi.yaml'
          - openapifilepath: 'api/v1/controller/openapi.yaml'

    steps:
      - name: Checkout
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Checkout
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: actions/checkout@v4

      - name: Validate OpenAPI definition By PR
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: char0n/swagger-editor-validate@v1
        with:
          definition-file: ${{ matrix.openapifilepath }}

      - name: Validate OpenAPI definition By Command
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: char0n/swagger-editor-validate@v1
        with:
          definition-file: ${{ github.event.inputs.path }}
