name: Auto Openapi Lint

on:
  push:
    branches:
      - main
      - release-*
    paths:
      - 'api/**/openapi.yaml'
  pull_request:
    branches:
      - main
      - release-*
    paths:
      - 'api/**/openapi.yaml'
  workflow_dispatch:
    inputs:
      ref:
        description: 'check for branch, sha, tag'
        required: true
        default: main
      path:
        description: 'openapi yaml path'
        required: true

jobs:
  link-check:
    name: Openapi Lint
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - openapifilepath: 'api/v1/agent/openapi.yaml'
          - openapifilepath: 'api/v1/controller/openapi.yaml'

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.ref || github.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install swagger-cli
        run: npm install -g @apidevtools/swagger-cli

      - name: Validate OpenAPI definition By PR
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: swagger-cli validate "${{ matrix.openapifilepath }}"

      - name: Validate OpenAPI definition By Command
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: swagger-cli validate "${{ github.event.inputs.path }}"
