name: Auto MarkDown Lint

on:
  push:
    branches:
      - main
      - release-*
      - github_pages
    paths:
      - "**.md"
  pull_request:
    branches:
      - main
      - release-*
      - github_pages
    paths:
      - "**.md"
  # checkout all markdown
  workflow_dispatch:
    inputs:
      ref:
        description: "check all md for branch, sha, tag"
        required: true
        default: main

jobs:
  markdown-link-check:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}

      - name: Checkout
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: actions/checkout@v4

      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.4.0
        with:
          files: .
          config_file: ".github/markdownlint.yaml"
          ignore_path: ".github/markdownlintignore"

      # - name: Run Spell Lint
      #  run: |
      #  make lint-markdown-spell
