// Code generated by go-swagger; DO NOT EDIT.

// Copyright 2022 Authors of spidernet-io
// SPDX-License-Identifier: Apache-2.0

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CoordinatorRoute Coordinator static route
//
// swagger:model CoordinatorRoute
type CoordinatorRoute struct {

	// dst
	Dst string `json:"dst,omitempty"`

	// gw
	Gw string `json:"gw,omitempty"`
}

// Validate validates this coordinator route
func (m *CoordinatorRoute) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this coordinator route based on context it is used
func (m *CoordinatorRoute) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CoordinatorRoute) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CoordinatorRoute) UnmarshalBinary(b []byte) error {
	var res CoordinatorRoute
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
